### ISSUE TITLE
add ssh uri matching

### ISSUE THREAD

**Issue by fredericmorinara** [jenkinsci/bitbucket-push-and-pull-request-plugin#103]
.When using ssh to clone from bitbucket server the SCM is not matched as it always seems to check against the https URL.

**Comment by cdelmonte-zg** [comment]
@fredericmorinara  ssh + https featue was already added. If you send me some logs, it could help. 
To collect the right logs, please refer to my comment in this issue:
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/100

**Comment by fredericmorinara** [comment]
We moved away from bitbucket and are not using this plugin anymore. Please close this issue.
