### ISSUE TITLE
Trigger build on new tags only

### ISSUE THREAD

**Issue by Gia90** [jenkinsci/bitbucket-push-and-pull-request-plugin#106]
Hi everyone,
I am trying to trigger a job on a `New tag pushed` event without success.

The trigger configuration looks like this: 
![image](https://user-images.githubusercontent.com/7150082/83510774-db235c00-a4cd-11ea-887f-74e5f87fd9c3.png)

When I push a new tag, the job is not triggered.

Everything works instead if I set the `Allowed Branches` filter either to:
- an empty string (which won't be an acceptable solution in my case, cause it will trigger the job on any push)
or
- to the exact tag name (which is not acceptable for me either, cause tag names are not fixed strings).

 
Is there a solution for this use case?

Thanks you guys.

**Comment by macghriogair** [comment]
Hi @Gia90, 
it sounds like we need another option for _**trigger only on tag push**_. Which currently is not supported but sounds like a viable enhancement. We'll have a look into it.

**Comment by rabadin** [comment]
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/119 seems a duplicate for this. Note that there is proposed pr: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/120.

**Comment by cdelmonte-zg** [comment]
Will be closed with the next release 2.4.1.
