### ISSUE TITLE
Build status propagation instructions

### ISSUE THREAD

**Issue by banjoh** [jenkinsci/bitbucket-push-and-pull-request-plugin#108]
PR #23 seems to have been merged. Its however not clear how to configure Jenkins to pass bitbucket credentials and any configuration parameters that are required to propagate build status information.

Are there plans to provide that? At the moment I plan to use this plugin in collaboration with a python script I'll write as per https://support.atlassian.com/bitbucket-cloud/docs/integrate-your-build-system-with-bitbucket-cloud/ instructions.

**Comment by cdelmonte-zg** [comment]
Hi @banjoh 

actually, the bitbucket credentials are the ones provided in the git plugin configuration for the job.
That means, that you don't need to give other credentials: it should work out of the box.

The only limit of this solution is that the build status propagation will work only if are using for the git plugin credentials of the kind: "Username with Password".

Besides that, it works actually only for the BitBucket Cloud.
The implementation for the BitBucket Server follows in the next days.

In any case, before we release the version 2.4.0 (hopefully during this weekend), we'll write all this in the Readme.

**Comment by banjoh** [comment]
Thanks for the prompt response!

I'm using Bitbucket Cloud so your solution works for me.

I was planning to give the python script a go on Monday but I'll try the credentials approach instead.

If you can, please add/copy (from bitbucket plugin README) instructions for adding a Jenkins webhook to a Bitbucket git repo as well
