### ISSUE TITLE
Build status "in progress" will be sent when the build is completed

### ISSUE THREAD

**Issue by Yayo-Arellano** [jenkinsci/bitbucket-push-and-pull-request-plugin#113]
The status "in progress" should be sent when the build starts and not when it completed. 

For a build that takes 15 minutes. The build status in progress and finish will be set in the end of the build

<img width="556" alt="Screen Shot 2020-06-24 at 10 22 24 PM" src="https://user-images.githubusercontent.com/3458265/85574395-50b3bf80-b669-11ea-84d5-8344f9488289.png">

**Comment by banjoh** [comment]
I'm experiencing the same problem

**Comment by andreijuc** [comment]
Experiencing the same issue here, also seems to be related to the 15 min mark.
