### ISSUE TITLE
Job Not Triggering For Bitbucket Server Pull Request

### ISSUE THREAD

**Issue by caseydaly** [jenkinsci/bitbucket-push-and-pull-request-plugin#115]
bitbucket-push-and-pull-request-plugin is not triggering a build for my Jenkins job, despite receiving a notification from Bitbucket that a pull request has been created.

You can see that after a pull request is created, Bitbucket sends a notification of the event to Jenkins via webhook, and it gets back a "200 OK" response...

![PR-Request](https://user-images.githubusercontent.com/26123193/86634441-b74cad80-bf86-11ea-902c-aab65ddba9e8.PNG)

![PR-Response](https://user-images.githubusercontent.com/26123193/86634448-b9af0780-bf86-11ea-96f3-7381d2c39a19.PNG)

If we look at my job configuration in Jenkins, it is as follows (should be building upon receiving a created Pull Request in Bitbucket Server).

![BuildTriggers](https://user-images.githubusercontent.com/26123193/86634511-cd5a6e00-bf86-11ea-9b0a-dc4d439d67db.PNG)

But, if we look at the logs regarding this pull request in Jenkins, we can see that even though we have received notification of the pull request getting opened, no job or build is triggered.

![Log1](https://user-images.githubusercontent.com/26123193/86635657-35f61a80-bf88-11ea-8738-2e201ea6ed08.PNG)

![Log2](https://user-images.githubusercontent.com/26123193/86635667-3b536500-bf88-11ea-8f29-abee817ca2df.PNG)

It considers both of my candidate jobs, and note that it DOES seem to acknowledge that I have a trigger set up on the last job it considers (because it doesn't display the message that no trigger was found for the last job), it has either mistaken the type of trigger that it is, or is ignoring it for whatever reason.

**Comment by cdelmonte-zg** [comment]
Hi @caseydaly ,

is the issue [#117](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/117) relevant for you?
