### ISSUE TITLE
How to merge approved pull requests in pipeline?

### ISSUE THREAD

**Issue by pratamov** [jenkinsci/bitbucket-push-and-pull-request-plugin#116]
my pull request status become `Approved` when the pipeline success, but not merged, how to merge it?

**Comment by cdelmonte-zg** [comment]
Hi @pratamov , you can merge the pull request using the BitBucket web console, for example. But maybe I didn't understand your question. Can you provide more context? Tnx.

**Comment by pratamov** [comment]
hi @cdelmonte-zg . Actually i am expecting in the end of pipelines, the plugin is also merging the merge request automatically, i don't know is it possible?

For bitbucket web console, no problem to click Merge button. I am looking for possibility to automate it also.

**Comment by JoaoPPCastelo** [comment]
Hi  @pratamov 
For what i saw, the plugin can't do it by itself, but you can do it as one of the last steps of your pipeline (i'm doing it that way). 

Something like:
```
// Checkout to target branch
sh "git checkout ${BITBUCKET_TARGET_BRANCH}"

// Merge source branch into target branch. Squash commits into just one.
sh "git merge ${BITBUCKET_SOURCE_BRANCH}"

// Push changes back to BitBucket
withCredentials([usernamePassword(credentialsId: 'BITBUCKET-CREDENTIALS', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
    sh 'git push https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.org/XXXXXXX/YYYYYYYYY.git'
}
```

**Comment by JoaoPPCastelo** [comment]
Hi  @pratamov 
For what i saw, the plugin can't do it by itself, but you can do it as one of the last steps of your pipeline (i'm doing it that way). 

Something like:
```
// Checkout to target branch
sh "git checkout ${BITBUCKET_TARGET_BRANCH}"

// Merge source branch into target branch. Squash commits into just one.
sh "git merge ${BITBUCKET_SOURCE_BRANCH}"

// Push changes back to BitBucket
withCredentials([usernamePassword(credentialsId: 'BITBUCKET-CREDENTIALS', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
    sh 'git push https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.org/XXXXXXX/YYYYYYYYY.git'
                    if (rc != 0) {
                        error 'Failed to push merge to BitBucket.'
                    }
                }
```

**Comment by pratamov** [comment]
thanks @JoaoPPCastelo , appreciate it
