### ISSUE TITLE
Jenkins pipeline isn't triggered by Bitbucket PR event

### ISSUE THREAD

**Issue by rabadin** [jenkinsci/bitbucket-push-and-pull-request-plugin#117]
Hi,

I'm trying to get a Jenkins pipeline job to run when a bitbucket PR is updated and I can't get it to work. I suspect I'm doing something wrong but I can't figure it out. Any help would be greatly appreciated. Here are the details:

### Versions

Jenkins version: 2.204.3
Bitbucket-push-and-pull-request-plugin version: 2.4.0
Bitbucket server version: v6.10.1

#### Trigger configuration
![Screen Shot 2020-07-22 at 14 06 25](https://user-images.githubusercontent.com/17436527/88174423-8fb34180-cc24-11ea-8702-d35aa928de9c.png)

#### SCM configuration
![Screen Shot 2020-07-22 at 14 12 56](https://user-images.githubusercontent.com/17436527/88175049-91c9d000-cc25-11ea-8a55-6a1be865469c.png)

#### Jenkinsfile
Jenkinsfile in the referenced repo:
```
#!groovy
pipeline {
  agent { label 'ci-runner' }
  stages {
    stage('Test') {
      steps {
        sh '''
          env
        '''
      }
    }
  }
}
```

### Logs

Enabling logs for the plugin:
```
Considering candidate job test-bitbucket
Jul 22, 2020 11:57:31 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke test-bitbucket
Jul 22, 2020 11:57:31 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job other-job
Jul 22, 2020 11:57:31 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke other-job
Jul 22, 2020 11:57:31 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: other-job is not present. 
```

### Analysis

Looking at the code it seems (based on the logs above) that the following line might be relevant: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/master/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRJobProbe.java#L110. `i.getSCMs() ` returns an empty list and thus nothing happens. My question is: if this is correct, what's missing in my configuration to get `i.getSCMs()` to not be empty?

**Comment by cdelmonte-zg** [comment]
Hi @rabadin 

the very strange thing is the line: "Bitbucket Trigger for job: other-job is not present." It should appear only when a job hasn't activated the bitbucket push and Pull requested filter or a scm is not specified.

It seems also that the same is happening as in the issue [115](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/115) 

Or do you see any differences?
Tnx

**Comment by rabadin** [comment]
Hi @cdelmonte-zg , thanks for looking at my issue, I appreciate it.

I have two jobs defined: one named `test-bitbucket` which has the `Bitbucket Push and Pull Request trigger` part enabled and another job named `other-job` which has nothing to do with bitbucket. So I think it's totally expected to get this message.

Again, looking at the code of the plugin it seems that the problem with the `test-bitbucket` job is that `getSCMs()` returns the empty list... shouldn't the config "Pipeline script from SCM" make it so that `getSCMs()` returns a non-empty list? In other words, you say `no scm was specified`... where is this supposed to be specified? It look like I'm missing something here.

I looked at issue #115 but judging by the logs there the problem seems different. In the logs that I have I don't even get passed the `getSCMs()` bit.

**Comment by cdelmonte-zg** [comment]
Is the jenkins log configured in this way?

![image](https://user-images.githubusercontent.com/23214236/88395987-2ec17000-cdc2-11ea-8756-6367e83e1210.png)

**Comment by rabadin** [comment]
@cdelmonte-zg Yes, it's configured exactly like this.

**Comment by cdelmonte-zg** [comment]
Okay, might you send me as text all the logs after substituting with meaningful strings (not using XXXs but job_1_abc, for example, so the references between the log lines are not getting lost) possible sensible data? That could be helpful

**Comment by rabadin** [comment]
@cdelmonte-zg Thanks again for looking into this. Actually, looking at the full log this seems awfully similar to #115.

Here is the full log:
```
Jul 24, 2020 2:35:30 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
Received commit hook notification : {"eventKey":"repo:refs_changed","date":"2020-07-24T07:35:30-0700","actor":{"name":"rabadin","emailAddress":"rabadin@company.com","id":34221,"displayName":"rabadin","active":true,"slug":"rabadin","type":"NORMAL","links":{"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin"}]}},"repository":{"slug":"test-integration","id":38437,"name":"test-integration","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"~RABADIN","id":17799,"name":"rabadin","type":"PERSONAL","owner":{"name":"rabadin","emailAddress":"rabadin@company.com","id":34221,"displayName":"rabadin","active":true,"slug":"rabadin","type":"NORMAL","links":{"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin"}]}},"links":{"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@bitbucket.company.com:7999/~rabadin/test-integration.git","name":"ssh"},{"href":"https://bitbucket.company.com/bitbucket/scm/~rabadin/test-integration.git","name":"http"}],"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin/repos/test-integration/browse"}]}},"changes":[{"ref":{"id":"refs/heads/test-pr2","displayId":"test-pr2","type":"BRANCH"},"refId":"refs/heads/test-pr2","fromHash":"abf7b2f08514dd04e16929a548ca07ab01569176","toHash":"e820978d2d5f9a554cb10f4b82bce10c8f2ec6dd","type":"UPDATE"}]}
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Received x-event-key repo:refs_changed from Bitbucket
Jul 24, 2020 2:35:30 PM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the payload is: {"actor":{"name":"rabadin","emailAddress":"rabadin@company.com","id":"34221","displayName":"rabadin","active":true,"slug":"rabadin","type":"NORMAL","links":{"clone":[],"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin"}]}},"repository":{"slug":"test-integration","id":"38437","name":"test-integration","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"~RABADIN","id":"17799","name":"rabadin","public":false,"type":"PERSONAL"},"links":{"clone":[{"href":"ssh://git@bitbucket.company.com:7999/~rabadin/test-integration.git","name":"ssh"},{"href":"https://bitbucket.company.com/bitbucket/scm/~rabadin/test-integration.git","name":"http"}],"self":[{"href":"https://bitbucket.company.com/bitbucket/users/rabadin/repos/test-integration/browse"}]},"public":false},"changes":[{"ref":{"id":"refs/heads/test-pr2","displayId":"test-pr2","type":"BRANCH"},"refId":"refs/heads/test-pr2","fromHash":"abf7b2f08514dd04e16929a548ca07ab01569176","toHash":"e820978d2d5f9a554cb10f4b82bce10c8f2ec6dd","type":"UPDATE"}]}
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPayloadProcessorFactory createProcessor
Create BitBucketPPRRepositoryServerPayloadProcessor
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.observer.BitBucketPPRObserverFactory createObservable
Add BitBucketPPRPushServerObserver for BitBucketPPREvent [event=repo, action=refs_changed]
Jul 24, 2020 2:35:30 PM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the selected payload processor is: io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRRepositoryServerPayloadProcessor@43769daa
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRServerRepositoryAction 
Received commit hook notification from server for destination branch: test-pr2
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRServerRepositoryAction 
Received commit hook type from server: UPDATE
Jul 24, 2020 2:35:30 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering remote [ssh://git@bitbucket.company.com:7999/~rabadin/test-integration.git, https://bitbucket.company.com/bitbucket/scm/~rabadin/test-integration.git]
Jul 24, 2020 2:35:30 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job test-bitbucket
Jul 24, 2020 2:35:30 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke test-bitbucket
Jul 24, 2020 2:35:30 PM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
Sending response.
Jul 24, 2020 2:35:30 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Response sent.
```

Additionally, here is the result of running:
```
import jenkins.triggers.SCMTriggerItem;

for (job in Jenkins.get().getAllItems(Job.class)) {
  println(job.getName());
  println(SCMTriggerItem.SCMTriggerItems.asSCMTriggerItem(job));
  println(job.getSCMs());
};
```
```
test-bitbucket
org.jenkinsci.plugins.workflow.job.WorkflowJob@42829c1d[test-bitbucket]
[]
```

**Comment by cdelmonte-zg** [comment]
@rabadin yes, it seems to be the same issue... 
Which version of the git plugin are you actually using?
And which is the BitBucket server version? 2.204.3 seems to be the jenkins one

**Comment by rabadin** [comment]
@cdelmonte-zg Right, the version of Bitbucket server was wrong in the issue (fixed now). The versions are:
Jenkins version: 2.204.3
Bitbucket-push-and-pull-request-plugin version: 2.4.0
Bitbucket server version: v6.10.1

**Comment by cdelmonte-zg** [comment]
@rabadin did you already triggered the job manually?

**Comment by rabadin** [comment]
@cdelmonte-zg No, I did not. Now that I've done it, I see that the job is correctly triggered from Bitbucket's events. So I guess that's what the problem was...

**Comment by cdelmonte-zg** [comment]
@rabadin that's a good news :) Does it mean that it is now working correctly? In that case, I would close the issue...

**Comment by rabadin** [comment]
@cdelmonte-zg Yes, it's working correctly. The fact that the job status isn't reported on the PR is going to be a problem for me but it's a completely unrelated problem and I see in the code it's simply not implemented yet.
Thanks for all your help on this, really appreciate it!
Closing the issue now.

**Comment by rabadin** [comment]
@cdelmonte-zg Out of curiosity, would you mind explaining why the job needs to be run manually once first? The reason why I'm asking is that I'm trying to see if it's possible to use this plugin in the context of a heavily automated setup where hundreds of jobs are created by automated scripts. Having to run things manually in this context is problematic and I'm trying to understand this better to see if there is a workaround.
