### ISSUE TITLE
Jenkins Pipeline is not getting triggered for new pull requests

### ISSUE THREAD

**Issue by archis99** [jenkinsci/bitbucket-push-and-pull-request-plugin#118]
Hi,

I am trying to run a Jenkins pipeline through bitbucket webhook for a new PR. Jenkins is receiving the webhook request from bitbucket and but the pipeline is not getting triggered. 

Please let me know if any setup I'm missing here.

Jenkins Version: 2.242
Bitbucket Server Version: 7.4.0
Bitbucket push and pull request plugin: 2.4.0

Jenkins Logs.
![image](https://user-images.githubusercontent.com/22589561/88480040-29eeee80-cf71-11ea-8aa6-6ab8c986d579.png)

Here is build trigger in Jenkins.
![image](https://user-images.githubusercontent.com/22589561/88478610-78978b00-cf67-11ea-9b2b-8a3d0189b5c1.png)

Webhook request details.
![image](https://user-images.githubusercontent.com/22589561/88478659-c0b6ad80-cf67-11ea-896e-66d16d32bc9e.png)

Webhook response details.
![image](https://user-images.githubusercontent.com/22589561/88478675-dcba4f00-cf67-11ea-8120-aa4f738af370.png)

**Comment by cdelmonte-zg** [comment]
Hi @archis99 

can you send the logs after setting the jenkins logging system for the bitbucket push and pull request plugin at level **"all"** as illustrated in this issue?  [https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/117](issue 117)

Tnx

**Comment by archis99** [comment]
Hi @cdelmonte-zg 

My bad. Now the pipeline is getting triggered with proper configuration. (The unit test class helped me out)
This issue can be closed.
