### ISSUE TITLE
Triggering a job only when tags are pushed

### ISSUE THREAD

**Issue by rabadin** [jenkinsci/bitbucket-push-and-pull-request-plugin#119]
What I'm trying to do here is have a job be triggered *only* when tags are pushed.

Here is the configuration I've tried:
![Screen Shot 2020-07-30 at 15 42 24](https://user-images.githubusercontent.com/17436527/88930099-4e054500-d27b-11ea-927d-163959d1fe89.png)
The problem seems to be that it's the tag name that's compared to my "Allowed Branches" and not the ref ID. Here is the log:
```
the target branch is: test-tag.
Jul 30, 2020 1:34:09 PM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.filter.repository.BitBucketPPRServerRepositoryPushActionFilter
The allowed branches are: refs/tags/*.
```

I wonder if this isn't a bug: reading the code I see that the plugin does not use the refId (`refs/tags/test-tag` in this case) but the `displayID` (`test-tag` in this case).

I'm applied the following change to the code, rebuilt the plugin:
```
--- a/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/action/BitBucketPPRServerRepositoryAction.java
+++ b/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/action/BitBucketPPRServerRepositoryAction.java
@@ -59,7 +59,7 @@ public class BitBucketPPRServerRepositoryAction extends InvisibleAction implemen

     for (BitBucketPPRServerChange change : payload.getServerChanges()) {
       if (change.getRefId() != null) {
-        this.targetBranchName = change.getRef().getDisplayId();
+        this.targetBranchName = change.getRef().getId();
         this.type = change.getType();
         break;
       }
```
and now I seem to be getting the behaviour I expect. Is this a bug or am I missing something?

**Comment by cdelmonte-zg** [comment]
Hi @rabadin, 

I'll check it in the WE and I'll let you know, tnx!

**Comment by rabadin** [comment]
Hi @cdelmonte-zg: cool, thanks for the heads up. When you get a chance, I also added a question related to the old issue that got closed recently: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/117#issuecomment-666371241. Many thanks!

**Comment by rabadin** [comment]
fwiw, I've put the change I suggest above in a PR: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/120

**Comment by cdelmonte-zg** [comment]
Will be closed with the release 2.4.1.

**Comment by macghriogair** [comment]
hello @rabadin, after a lot of internal discussion we decided to introduce a new filter option _triggerOnlyIfTagPush_ for the desired feature. Even if with your changes it works for Server tag pushes, it wouldn't work for the cloud payloads. Still the workaround provided by your PR should not be affected. 🙂

**Comment by rabadin** [comment]
Thanks for the heads up @macghriogair!
