### ISSUE TITLE
Job is not triggering when Two jobs with one repo

### ISSUE THREAD

**Issue by gudipudipradeep** [jenkinsci/bitbucket-push-and-pull-request-plugin#127]
I Have create two job for one code repo.
Development --> trigger for Created
Integration --> trigger for Merged

Whenever I merged the code Integration is working with Merge trigger. but Development is not working whenever I push the code changes.
Configuration is same for dev and integration only trigger configuration.
Development Job configuration. Please help me 
![image](https://user-images.githubusercontent.com/8638634/95553676-a3549400-0a2c-11eb-91eb-909ccd4e199d.png)
![image](https://user-images.githubusercontent.com/8638634/95553638-920b8780-0a2c-11eb-9525-84c313f5ccbc.png)

**Development Job Log:**
Started on Oct 8, 2020 1:55:03 PM
Workspace is offline.
Awaiting build to get a workspace.
Done. Took 0 ms
No changes

**Comment by gudipudipradeep** [comment]
Above issue solved. Please can you help on below use case.

### Build has to trigger after creation of pull request as well push the changes on top of pull request when ever they do. 
what are all option I need to select in plugin as well as Bitbucket.

I do not want normal push trigger because it is not bind with pull request creation

**Comment by macghriogair** [comment]
Closing this as I understand the initial issue was solved. For the latter, please open a new issue.
