### ISSUE TITLE
[Question] Is it possible to access the event type or string (X-Event-Key) from DSL scripts?

### ISSUE THREAD

**Issue by levente-staub** [jenkinsci/bitbucket-push-and-pull-request-plugin#130]
I'm using Bitbucket Cloud and I was wondering if it is possible to access the event type (create PR, update PR, merge PR, etc...) that triggered the build from DSL scripts so I can handle multiple events in the same script.

**Comment by macghriogair** [comment]
Hey @levente-staub , currently the request header containing the `x-event-key` is not passed through as environment variable. However it should be possible to implement it.

**Comment by macghriogair** [comment]
coming with next release see #136

**Comment by cdelmonte-zg** [comment]
Added with release 2.5.1
