### ISSUE TITLE
missing environment  variables for multi configuration  

### ISSUE THREAD

**Issue by gudipudipradeep** [jenkinsci/bitbucket-push-and-pull-request-plugin#132]
@cowboyd  for multi configuration  projects following environment  variable are missing. Please help me
All env Variables starting with BITBUCKET
Like below
'BITBUCKET_TARGET_BRANCH' in '$BITBUCKET_TARGET_BRANCH
 @cris

**Comment by macghriogair** [comment]
Can you elaborate a bit on this? What do you mean by "All env Variables starting with BITBUCKET"? Can you provide logs please?

**Comment by gudipudipradeep** [comment]
For matrix(https://plugins.jenkins.io/matrix-project/) project BITBUCKET_ environment variable are not delegating for matrix configuration.
Matrix Configuration:
![image](https://user-images.githubusercontent.com/8638634/97268696-44778300-1852-11eb-8c7e-24e1941b2624.png)

![image](https://user-images.githubusercontent.com/8638634/97268814-77ba1200-1852-11eb-8692-f770d9e8cdc1.png)

![image](https://user-images.githubusercontent.com/8638634/97268898-9c15ee80-1852-11eb-99d0-bab397bb1f6c.png)

Matrix Configuration missing BITBUCKET_ environment variable.

**Comment by cdelmonte-zg** [comment]
Hi @cowboyd, thanks. The feature is now merged in master and it will be released in the v2.5.2

**Comment by cdelmonte-zg** [comment]
v2.5.2 released

**Comment by gudipudipradeep** [comment]
@cdelmonte-zg  @cowboyd  thanks for you are quick fix.
