### ISSUE TITLE
PUSH webhook doesn't trigger job in multi branch pipeline

### ISSUE THREAD

**Issue by pdorval** [jenkinsci/bitbucket-push-and-pull-request-plugin#134]
mPJobShouldNotBeTriggered function doesn't return the good response when trigerred from a push...

**Comment by pdorval** [comment]
obtaining this log when receiving a push webhook trying to trigger my job in multi branch pipeline


`Considering to poke patate » master
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to use trigger hudson.plugins.git.GitSCM@370bbda7
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Job is of type: org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket event is : push
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Job Name : master
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
sourceBranchName: null 
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
targetBranchName : master
Oct 22, 2020 2:36:29 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Skipping for job:master`

**Comment by Sleepy-GH** [comment]
I think there's a few duplicates of this issue and a PR has already been created: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/135

**Comment by cdelmonte-zg** [comment]
Solved with release 2.5.1
