### ISSUE TITLE
Pattern for allowed branches

### ISSUE THREAD

**Issue by kagarlickij** [jenkinsci/bitbucket-push-and-pull-request-plugin#14]
Hi there, 
First of all many thanks for this nice plugin!
I have a suggestion - is it possible to add pattern for Allowed branches? 
Right now this config doesn't work - http://prntscr.com/n9a5ti
..but this does - http://prntscr.com/n9a5zf
Thanks in advance!

**Comment by AntonTyutin** [comment]
Hi! Eagerly waiting this feature
:+1:

**Comment by AntonTyutin** [comment]
Does `hudson.plugins.git.BranchSpec` makes difference between `*/*` and `*/**` patterns? Need this feature interprets `*/*` like the GitPlugin do.

**Comment by cdelmonte-zg** [comment]
It works in the same way 👍
