### ISSUE TITLE
Silence notifications

### ISSUE THREAD

**Issue by michalip** [jenkinsci/bitbucket-push-and-pull-request-plugin#142]
Hi 
Is there a way or can we get a checkbox to disable sending notifications back to bitBucket?

Thanks

**Comment by macghriogair** [comment]
Hello @michalip , 
so you are referring to the propagation of the BuildStatus to Bitbucket, right? This would be a feature request we need to check.
Are you experiencing issues with the current implementation?

**Comment by michalip** [comment]
Hi @macghriogair, 
Not experiencing issues but I had to disable my current notifications which I had setup for every try-catch , because they were recording the build status twice on BitBucket. 
If I had an option to disable I would take that ; the only reason is that I provide  a description for my builds like CI-XXX-## , while form the plugin it only comes as a number #

**Comment by SirMrDexter** [comment]
@macghriogair please check the issue I reported in stashnotifier repo. We have the status notification reported via that plugin already and the notifications from BPPR are causing a bit of confusion for us and at present we have no way to turn it off.

**Comment by SirMrDexter** [comment]
While working on the fix, found a workaround. If you remove credentials from the git repo, it skips sending update. The other status notification plugin we use have the option to supply credentials to use when sending status notifications. So that was a work around, we were able to use until the fix is released.

**Comment by macghriogair** [comment]
Support to disable the notification via global config added in v2.7.0

**Comment by michalip** [comment]
awesome , cant wait to try it out . Thanks
