### ISSUE TITLE
PR that trigger simultaneously will override one another

### ISSUE THREAD

**Issue by hebrewd** [jenkinsci/bitbucket-push-and-pull-request-plugin#146]
Using the plugin, we noticed that if users will trigger two PR in a short time window, jenkins will pick the last of them and ignore the first, the log indicate that jenkins did get notified for both via the webhook:

```
15:47:02 Started by user <username>: Bitbucket PPR: pull request updated
15:47:02 Started by user <username>: Bitbucket PPR: pull request updated
15:47:02 Running as SYSTEM
15:47:02 Building in workspace /var/lib/jenkins/workspace/vayadrive
15:47:02 [WS-CLEANUP] Deleting project workspace...
15:47:02 [WS-CLEANUP] Deferred wipeout is used...
15:47:02 [WS-CLEANUP] Done
...
```
There are two 'started by user' messages, though they both should trigger two different build pipes.

**Comment by hexonxons** [comment]
Seems like I have the same issue, but I'm not sure.

If we push to same PR several commits quite fast, latter commits will not trigger new job.

E.g:
I have a pull request in bitbucket.
I push commits to that PR:
```
for i in {1..4}; do echo 1 >> 1 && git add . && git commit -m $(date '+%Y%m%d-%H%M%S-%N') && git push --force; done
```
I'm expecting 4 jobs being triggered, but only 1 or 2 jobs starts(depends on jenkins job pending settings) . Also BBPPR sends build status to all 4 commits, not for the one built by Jenkins.

Full BBPPR log file of that call: [jenkins.bbppr.log](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/files/5666133/jenkins.bbppr.log)
