### ISSUE TITLE
BITBUCKET_X_EVENT not populated with full eventKey.

### ISSUE THREAD

**Issue by wanderboessenkool** [jenkinsci/bitbucket-push-and-pull-request-plugin#152]
The environment variable BITBUCKET_X_EVENT is not populated with the correct values.

Instead of values like `pr:opened` or `repo:refs_changed` it is filled with values like `pr` and `repo`. A cursory grep through the sources makes me believe it has something to do with the `event` being split from the `action` in src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/model/BitBucketPPRHookEvent.java line 52.

This currently blocks me from acting on certain scenarios from a single pipeline, since the `eventkey` field is also stripped from the payload environment variable.

**Comment by cdelmonte-zg** [comment]
Hi @wanderboessenkool,

thank you for reporting the issue. It's going to be fixed in the release 2.6.3, out today.
Chr
