### ISSUE TITLE
Guidance for migrating from bitbucket plugin?

### ISSUE THREAD

**Issue by HolisticDeveloper** [jenkinsci/bitbucket-push-and-pull-request-plugin#159]
Is there any guidance for migrating from the [original bitbucket plugin](https://plugins.jenkins.io/bitbucket/)? We have several jobs using the original; if we uninstall that and use this one instead, is it necessary to reconfigure all the settings?

**Comment by cdelmonte-zg** [comment]
Hi @HolisticDeveloper ,

the jobs need to be reconfigured. As I remember, the bitbucket plugin doesn't have options at all. Did it change in the last two years?

**Comment by HolisticDeveloper** [comment]
It looks like most of the settings I was thinking of are related to the git plugin, not the bitbucket one. For bitbucket, the only option I see is the override URL (which I don't think we make use of).

I'm working on a solution where I can iterate over all the jobs and update the XML build configuration for them. For the existing jobs, the "Build when a change is pushed to BitBucket" option shows up like so in the XML:

```xml
<project>
  <triggers>
    <com.cloudbees.jenkins.plugins.BitBucketTrigger plugin="bitbucket@1.1.25">
      <spec/>
      <overrideUrl/>
    </com.cloudbees.jenkins.plugins.BitBucketTrigger>
  </triggers>
</project>
```

Do you have an example of how this new plugin would look? If not, I can set up a test Jenkins server and try it out.

**Comment by cdelmonte-zg** [comment]
Hi @HolisticDeveloper, 

changing to BB PPR the configs of all other plugins you are using should not get lost, as far as I know.
The only think to keep in mind, is that you need to uninstall the Bitbucket Plugin.

For testing, maybe you could simply create a new job using  the function "copy from".

**Comment by HolisticDeveloper** [comment]
Awesome! I'll check back if I have any other questions.
