### ISSUE TITLE
Only builds latest commit on master if no Git filter matches source branch

### ISSUE THREAD

**Issue by haliphax** [jenkinsci/bitbucket-push-and-pull-request-plugin#163]
I don't see any way to get Jenkins to build a pull request from BitBucket Server (hosted), as it just builds the latest commit for whatever the destination repository is. I can't rely on the pull request refs any longer, but I also cannot specify the commit ID to checkout, as the commit ID is not provided in any of the build parameters nor environment variables (except buried in BITBUCKET_PAYLOAD, which I cannot use in the SCM step).

Is there something I'm missing? Is this documented somewhere? Whenever anyone makes a PR to master, it just builds whatever was at the tip of master (which is what master looked like _before_ the PR)...

**Comment by macghriogair** [comment]
Hello @haliphax ,
could you provide more details how you configured the job and maybe logs (with sensitive content redacted), please?

**Comment by macghriogair** [comment]
Did you find a solution to your problem or is this still an issue?

We could reproduce this behaviour the following way:

- add a branches filter in the **Git plugin** config for "master"
- then create a PR from `develop` to `master`

Result: a build on `master` is triggered as you said which is not expected.

The workaround would be to add a branch filter that matches the source branch, e.g.
- "develop" or "feature/*" etc.
or
- set the filter to any "*" in the Git plugin.

Anyway, we should further investigate why the build is triggered on master in the second place (when no filter matches the source branch).

**Comment by haliphax** [comment]
We don't want to filter on *, because we don't want to build every branch. We want to build pull requests against master. However, as I stated before, nothing we need about the PR branch/commit/repo is included in the environment variables in a usable manner. It's not an issue because I use a different plugin to accomplish this; one that does provide information about the incoming pull request as variables that I can then provide to the SCM step of the build.

**Comment by haliphax** [comment]
![image](https://user-images.githubusercontent.com/745888/111648526-73769d00-87d1-11eb-8e0c-7a31eedb92ac.png)

Here is a screenshot of how we are using Stash Pull Request Builder's variables.

**Comment by macghriogair** [comment]
If I understand you correctly, you have found a solution to your problem.

Also, thank you for pointing to the [Stash Pull Request Builder Plugin](https://plugins.jenkins.io/stash-pullrequest-builder/). 
Just now I understood that you are trying to merge a feature into master (locally) to then build it as part of the job.
We will add the env variable for the source commit hash shortly in the next release.

Please re-open in case it's still an issue.
