### ISSUE TITLE
Bitbucket Trigger for job is not present

### ISSUE THREAD

**Issue by dsaydon90** [jenkinsci/bitbucket-push-and-pull-request-plugin#169]
Hi!

I'm trying to configure webhook so on any change on the bitbucket scm it will trigger my job by webhooks.
I'm trying to do this with `multi branch pipeline`

it seems that the jenkins got the webhook
```
2021-03-10 11:17:56.638+0000 [id=534]	INFO	i.j.p.b.BitBucketPPRHookReceiver#doIndex: Received x-event-key: repo:push from Bitbucket
2021-03-10 11:17:56.640+0000 [id=534]	INFO	i.j.p.b.p.BitBucketPPRPayloadProcessorFactory#createProcessor: Create BitBucketPPRRepositoryCloudPayloadProcessor
2021-03-10 11:17:56.640+0000 [id=534]	INFO	i.j.p.b.o.BitBucketPPRObserverFactory#createObservable: Add BitBucketPPRPushCloudObserver for BitBucketPPREvent [event=repo, action=push]
2021-03-10 11:17:56.640+0000 [id=534]	INFO	i.j.p.b.p.BitBucketPPRRepositoryCloudPayloadProcessor#buildActionForJobs: Instantiate BitBucketPPRRepositoryAction
2021-03-10 11:17:56.641+0000 [id=534]	INFO	i.j.p.b.a.BitBucketPPRRepositoryAction#<init>: Received commit hook notification for branch: development-k8s
2021-03-10 11:17:56.641+0000 [id=534]	INFO	i.j.p.b.a.BitBucketPPRRepositoryAction#<init>: Received commit hook type: branch
2021-03-10 11:17:56.645+0000 [id=534]	INFO	i.j.p.b.BitBucketPPRHookReceiver#doIndex: Response sent.
```

but in the logs it seems that it's not finding the right jenkins multi branch pipeline job
```
Considering candidate job development-k8s
Mar 10, 2021 11:22:12 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke repositories » wsserver » development-k8s
Mar 10, 2021 11:22:12 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: repositories » wsserver » development-k8s is not present. 
Mar 10, 2021 11:22:12 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
```
even that this job exist
![image](https://user-images.githubusercontent.com/22152786/110623085-034e9280-81a5-11eb-96cd-767bd07c6b4d.png)

with this configurations
![image](https://user-images.githubusercontent.com/22152786/110623198-34c75e00-81a5-11eb-9fec-cd90243823db.png)

it seems in the code that `bitbucketTrigger` is `null`
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/c088d819ab112aa15ea47463ff8420520b5e5f28/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRJobProbe.java#L108
and the error:
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/c088d819ab112aa15ea47463ff8420520b5e5f28/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRJobProbe.java#L149

I can see that you are support `multi branch pipeline` from here: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/135

What AM I doing wrong?

Env:
Jenkins 2.263.2
![image](https://user-images.githubusercontent.com/22152786/110660893-b1b9fe00-81cc-11eb-85b8-2ef85afc5850.png)

**Comment by macghriogair** [comment]
Hello @dsaydon90,
have you configured a trigger via the Jenkinsfile that is checked in on the branch? If so, could you please post how you configured it?

**Comment by dsaydon90** [comment]
Hi @macghriogair , I haven't configured because I have used the **Bitbucket** branch source
Do I have to configure in my `Jenkinsfile`?
it yes, `triggers` is enough ?
```
  ...
  triggers{
    bitbucketTriggers {
      pullRequestCreatedAction()
    }
  }
  ...
``` 
OR do I have also to add a `remote` of my git url?
```
  scm {
    git {
      remote {
        url("<git repo url>")
      }
    }
  }
```
Thanks!

**Comment by macghriogair** [comment]
Hi @dsaydon90,
configuring the trigger should be sufficient. See https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin#pipeline-script for examples. You can also generate the code via the "Pipeline Syntax" helper tool in Jenkins.

**Comment by dsaydon90** [comment]
it seems that adding the following `triggers` in my jenkins declarative pipeline worked
```
    triggers {
        bitBucketTrigger([
            [$class: 'BitBucketPPRRepositoryTriggerFilter', actionFilter: [$class: 'BitBucketPPRRepositoryPushActionFilter', allowedBranches: '', triggerAlsoIfNothingChanged: true, triggerAlsoIfTagPush: true, triggerOnlyIfTagPush: false]], 
            [$class: 'BitBucketPPRPullRequestTriggerFilter', actionFilter: [$class: 'BitBucketPPRPullRequestCreatedActionFilter', allowedBranches: '']], 
            [$class: 'BitBucketPPRPullRequestTriggerFilter', actionFilter: [$class: 'BitBucketPPRPullRequestUpdatedActionFilter', allowedBranches: '']]
        ])
    }
```
and also configuring the bitbucket webhook like this (for my case)
![image](https://user-images.githubusercontent.com/22152786/115395963-254c2380-a1ed-11eb-8e31-5b08e0b3d5ea.png)
