### ISSUE TITLE
[Feature Request] add a trigger action for denied PR

### ISSUE THREAD

**Issue by HeidiRechek** [jenkinsci/bitbucket-push-and-pull-request-plugin#173]
There is actions that should happen if a PR is declined.  They webhook has the ability to push the Declined event, but the jenkins plugin doesn't have a action for that to trigger on. 

Our use case is that on PR Create we allocate an on demand sandbox, on Merge it is cleaned up, on decline, it is currently orphaned. We want to automate cleanup on "declined:

**Comment by y0zg** [comment]
@HeidiRechek just wondering whether you managed to solve the issue
In my case I don't need PRs to be declined whenever jenkins job is failed. Any ideas how to do this?
