### ISSUE TITLE
Branch reindexing trigger

### ISSUE THREAD

**Issue by Sleepy-GH** [jenkinsci/bitbucket-push-and-pull-request-plugin#175]
Hey folks,

Just wanted to double check something. Does this plugin trigger any branch reindexing upon receipt of a push (or any other) webhook notification from Bitbucket? It doesn't seem to be doing this for me.

Thanks

**Comment by cdelmonte-zg** [comment]
Hi @Sleepy-GH,

generally speaking, the BBPPR plugin relegates the git plugin all SCM related functionalities.

Could you give any use case example?
Thanks

**Comment by Sleepy-GH** [comment]
Alright, it might also have been some confusion on my end. I have the plugin installed, multibranch pipeline configured, and have the triggers in my Jenkinsfiles and that all works fine. I was just (wrongly) thinking that the webhook which is used to triggers builds also scans for new branches.

I have branch discovery working now in the sense that I now also registered a webhook in Bitbucket for the Bitbucket Branch Source plugin. Could be something worth documenting.

**Comment by dsaydon90** [comment]
Hi @cdelmonte-zg,  1 use case case can be new branch creation

It seems that I have created new branch called `development-test1`
```
Apr 20, 2021 12:13:21 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
sourceBranchName: null 
Apr 20, 2021 12:13:21 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
targetBranchName : development-test1
```

The webhook has been sent successfully, but because the branch wasn't exist nothing was triggered

another scenario can be new PRs like: `PR-1`, `PR-2`, `PR-3` and etc..

it seems that reindexing can help here
