### ISSUE TITLE
Getting 200 status code but Unable to Trigger job using bitbucket-push-and-pull-request plugin.

### ISSUE THREAD

**Issue by Jpanda124** [jenkinsci/bitbucket-push-and-pull-request-plugin#178]
Hello,

I have installed and configured bitbucket-push-and-pull-request plugin .
Before installation of this plugin , I have uninstalled Bitbucket old plugin .

I am using Jenkins version : Jenkins 2.249.3
Bitbucket Push and Pull Request plugin version : 2.7.2

After configuration , from bitbucket webhook section getting 200 status response .
for webhook configuration , I have selected pullrequest opened so that each time a new pull request raised, Jenkins should trigger the job automatically  .

![image](https://user-images.githubusercontent.com/80794653/116638357-30612b00-a934-11eb-97e7-5052ff83abf9.png)
![image](https://user-images.githubusercontent.com/80794653/116638410-453dbe80-a934-11eb-8225-c9822fd74a72.png)

In the Jenkins configuration I have added the configuration for Build with BitBucket Push and Pull Request Plugin

![image](https://user-images.githubusercontent.com/80794653/116637379-c0ea3c00-a931-11eb-9f7b-f36e6540999d.png)

![image](https://user-images.githubusercontent.com/80794653/116637502-1c1c2e80-a932-11eb-8460-a33cacff4eee.png)

When I am running manually , jenkins job running fine .
But for each new pull request job not running .

I added the logger to track the issue .

I can see the logs generating for **io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver** after a new PR raised.
I can see the logs for **io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe** after a new PR raised.
Seems in **BitBucketPPRJobProbe** function It can detect which job has the bitbucket push and pull request configuration .
but its not going to trigger function .

**There is no log for io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRTrigger**

I am suspecting the issue is happening for below section
**List<SCM> scmTriggered = new ArrayList<>();
 Optional<SCMTriggerItem> item = Optional.ofNullable(SCMTriggerItem.SCMTriggerItems.asSCMTriggerItem(job));**

Can anyone please help me to fix the issue . Why I am unable to run the jenkins job for each pull request.
I want to use this plugin as this plugin can give value add to multiple applications of my organization .

Thank you .

**Comment by Jpanda124** [comment]
Issue has been resolved .

**Comment by rxsheng** [comment]
how to resolve this issue

**Comment by marcopaggioro** [comment]
How was it resolved?
