### ISSUE TITLE
[help] Failed pipeline should not decline the PR and just report on the PR

### ISSUE THREAD

**Issue by kumarpratyush** [jenkinsci/bitbucket-push-and-pull-request-plugin#195]
Currently the failed pipeline declines the PR. After that the developer has to make changes, push commit and raise the PR again. Is there any way to ensure that the failed pipeline's status is just posted on the PR and does not decline the PR?

**Comment by kumarpratyush** [comment]
Closing as I had enabled the `Allow Jenkins to approve PR` option

**Comment by y0zg** [comment]
@kumarpratyush hi, can you please provide more details on your workaround? I need to prevent PR to be declined whenever Jenkins job is failed. Where is this option available? `Allow Jenkins to approve PR`

**Comment by kumarpratyush** [comment]
This option comes in the `configure` page of any job. 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/5759281/140721886-075508a5-ffe3-445d-b17a-25d155cd483b.png">

**Comment by y0zg** [comment]
@kumarpratyush Thanks for your answer 
I'm just trying to understand whether we are talking about the same scenario like I posted here https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/199

I have also this option enabled **Let Jenkins approve the event on BitBucket** but whenever pipeline fails, PR is also declined. 

Am I correct that in your case PRs are not declined but only get approved? If yes, it's very interesting

**Comment by y0zg** [comment]
@kumarpratyush That's correct, so in your case Jenkins doesn't approve any PRs, am I correct?
Asking as I have the same issue and I need only Jenkins approval for PRs but not PRs decline https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/199

**Comment by kumarpratyush** [comment]
As mentioned in #199 , they both work in tandem. If you select this check box, it will decline for failure and approve for success.

**Comment by y0zg** [comment]
Yep, I wonder if you approve PRs within CICD pipelines in different manner
