### ISSUE TITLE
pipeline shouldn't be trigged when there is merge conflict

### ISSUE THREAD

**Issue by y0zg** [jenkinsci/bitbucket-push-and-pull-request-plugin#207]
At least, pipeline shouldn't be triggered when there is merge conflict.
Second point I wonder how to identify properly such merge conflicts with jenkins pipeline like it's done in bitbucket.
Any thoughts?

**Comment by cdelmonte-zg** [comment]
Hi @y0zg 

Thanks, it's a good point.
I would move this issue into the discussions. Is it okay for you?

**Comment by y0zg** [comment]
hi @cdelmonte-zg , sure!
