### ISSUE TITLE
Jenkins pipeline job not triggered on created pull request

### ISSUE THREAD

**Issue by markobogoevski** [jenkinsci/bitbucket-push-and-pull-request-plugin#241]
Hello. 

I am trying to call a pipeline job in Jenkins whenever a new pull request towards a certain branch is created (let it be master). Scenario: developer creates a new branch feature/... and eventually opens a PR for merging the feature branch into the master branch. Whenever this happens I want Jenkins to trigger a pipeline job which should check the build for the PR. 

I am running Jenkins 2.323 and for bitbucket integration am using this [plugin](https://plugins.jenkins.io/atlassian-bitbucket-server-integration/)

I have created a webhook for the repository in bitbucket like this:
![image](https://user-images.githubusercontent.com/32468453/148987892-05ce05e5-3498-4f8b-b507-0ac649aa07f5.png)

The details for the 400 error are these:
![image](https://user-images.githubusercontent.com/32468453/148988313-c73c54af-adc0-42a6-a09b-a35113bf5d5d.png)

In the URL I have added the default bitbucket-hook/ at the end

On the Jenkins configuration side:
![image](https://user-images.githubusercontent.com/32468453/148988585-c6903a0f-e5c4-4cc4-acce-6a146b030439.png)

The pipeline job:
![image](https://user-images.githubusercontent.com/32468453/148988784-f76d8be3-3433-4050-995d-e6711e3abbbe.png)

The job runs a scripted pipeline which checks for changes and runs several other jobs based on that

The Jenkins logs:
![image](https://user-images.githubusercontent.com/32468453/148989045-deaaa132-b622-4bc7-8795-42fda2e7a8d1.png)

This gets logged whenever I create a pull request towards the branch

What's interesting is that on the bitbucket webhook side I get this:
![image](https://user-images.githubusercontent.com/32468453/148989235-4c82e944-ff64-4113-9f9f-21474b96230b.png)

with these details:
![image](https://user-images.githubusercontent.com/32468453/148989292-cf1646ee-f9f8-4eb6-9ac3-00bc9462fd60.png)

I've tried running the job once, but still doesn't work. It keeps logging that a trigger hasn't been set. What is the problem?

**Comment by y0zg** [comment]
Leave Allowed branches as blank

**Comment by cdelmonte-zg** [comment]
Hello @markobogoevski 

It is partially the same issue as #243 (400 response on test connection)
Did you solve the second part of the issue, leaving blank the filter on the branches as suggested by @y0zg ?

**Comment by sudaan** [comment]
Got the same issue. And the plugin used to work in older version. We configure the branch pattern with "**". In the Jenkins log, it failed to match the multi SCM.

**Comment by sudaan** [comment]
we solved this issue by changing the url from ssh to https in the SCM. And test connection return 200 from the bitbucket Webhook page.

**Comment by Chivolta** [comment]
I have the same problem. Downgraded to 2.7.2 helped.

**Comment by sudaan** [comment]
We also found that the uppercase and lowercase letters in url might be matter. We used to have some uppercase letter in the url (e.g. project code), after we change full url to lowercase, the plugin works again

**Comment by cdelmonte-zg** [comment]
Hello @markobogoevski, @Chivolta, @sudaan and @y0zg

I just released the beta release ## 2.8.2-beta-1 for this bug
Is the issue still present?

Tnx
Cdm

**Comment by jsj1027** [comment]
@cdelmonte-zg I'm actually having this issue right now on plugin version 28.2-beta-1 and Jenkins version 2.332.3.
Im guessing it has to do with the Job not being created until a manual build is run?

I ran this code on the jenkins scipt console. And the branch does not come up as having a corresponding Job. A workaround I was able to use was by triggering the build manually the first time. But that's not great. 
```
import io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRTrigger


Jenkins.get().getAllItems(Job.class).stream().each{ job ->  
  println "${job.fullName}"
  
}```

**Comment by ofri-7chairs** [comment]
I've upgraded to version 2.8.3 and still nothing has been triggered.
I'm able to see on the logs the payload from bitbucket (on 2.8.1 the payload was empty) but the job is not being triggered.
I already run the job couple of times manually.
