### ISSUE TITLE
HTTP ERROR 403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by RohitGagan16** [jenkinsci/bitbucket-push-and-pull-request-plugin#242]
My jenkins version is 2.319.1
Bitbucket PPR plugin version is 2.8.1. Getting the error as 

I am trying to trigger the jenkins job with bitbucket PR creation but this shows the below error

Getting this error while setting up the webhookl for bitbucket PPR 
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>

**Comment by zbuh** [comment]
Having the same issue...

**Comment by curtisgcarroll** [comment]
Are you sure you have installed and configured the plugin correctly on Jenkins? I received this error when the webhooks had been setup on bitbucket but Jenkins was not properly configured. Are you using a custom url? If you make config changes, you will need to restart Jenkins as well.

**Comment by zbuh** [comment]
Fixed if by removing '/' from the custom URL config

**Comment by klin111** [comment]
very good  Don't need  "/"  in the  custom hook URL config.
