### ISSUE TITLE
Add environment variable for git repository url

### ISSUE THREAD

**Issue by chickenpie3** [jenkinsci/bitbucket-push-and-pull-request-plugin#26]
# Feature Request
Add an environment variable for the git repository url, e.g. https://bitbucket.org/owner/repository

# Feature description
This would allow a single jenkins job to build pull requests for multiple repositories

# Possible Implementation
This value is in the bitbucket payload: payload.pullrequest.source.repository.links.href.html

**Comment by macghriogair** [comment]
Hello @chickenpie3 ,
thank you for your request.

I don't think this is possible at the moment.

While it would be easy to add the environment variable from the payload, the plugin depends on a _concrete repository_ being assigned to the job. 
Basically, it looks through all the Jenkins jobs that match the repo url in the payload and if it finds one, it will trigger the vinculated job. So what you expect from it will not work. You will need to configure dedicated jobs for each repo.

**Comment by chickenpie3** [comment]
@macghriogair I understand what you mean.
I havent found any plugin that does what I want, but its not a big deal, I can create dedicated jobs. It will just take some time :/
