### ISSUE TITLE
triggered error   "SCM doesnt match remote repo {1} or it was already triggered."

### ISSUE THREAD

**Issue by klin111** [jenkinsci/bitbucket-push-and-pull-request-plugin#265]
`Jun 16, 2022 9:35:43 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.receiver.BitBucketPPRHookReceiver doIndex

Received POST request over Bitbucket hook

Jun 16, 2022 9:35:44 AM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.receiver.BitBucketPPRHookReceiver

the payload is: {}

Jun 16, 2022 9:35:44 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPayloadProcessorFactory createProcessor

Create BitBucketPPRRepositoryServerPayloadProcessor

Jun 16, 2022 9:35:44 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.observer.BitBucketPPRObserverFactory

Add BitBucketPPRPushServerObserver for {}

Jun 16, 2022 9:35:44 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRServerRepositoryAction 

Received commit hook notification from server for destination branch: feature/one

Jun 16, 2022 9:35:44 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRServerRepositoryAction 

Received commit hook type from server: BRANCH

Jun 16, 2022 9:35:44 AM WARNING io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe lambda$triggerMatchingJobs$1

Trigger not set

Jun 16, 2022 9:35:44 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe

**_test-restart SCM doesnt match remote repo {1} or it was already triggered._**

Jun 16, 2022 9:35:44 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe

**_test-push-pr SCM doesnt match remote repo {1} or it was already triggered._**
`

**Comment by klin111** [comment]
- Webhook event details

- Response details
HTTP status:200
Duration457ms

- Headers
Date: Thu, 16 Jun 2022 01:35:44 GMT
Transfer-Encoding: chunked
Server: nginx
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Via: 1.1 localhost (Apache-HttpClient/4.5.13 (cache))

- Body
Bitbuckt PPR Plugin: request received successfully.

**Comment by klin111** [comment]
how to fix  that  "SCM doesnt match remote repo {1} or it was already triggered"

**Comment by klin111** [comment]
I have solved this problem。 SCM  git URL  needs to be the same as  in the  bitbucket  Webhooks's  requests body  item "clone" URL

**Comment by mdsnassor** [comment]
Hallo klin11,

is there by any chance illustrate your solutions. I kinda have the same problem but i didn't understand the SCM git url because i haven't configured that anywhere

**Comment by eylon23** [comment]
Dear@klin111,
you could be more specific on how you solved it? I also have the same issue
