### ISSUE TITLE
pipeline build not triggered for PR create or update

### ISSUE THREAD

**Issue by gmarzot** [jenkinsci/bitbucket-push-and-pull-request-plugin#268]
using jenkins 2.356 or 2.346.1 and bpprp 2.8.1 . basic pipeline job with triggers set as follows:

![image](https://user-images.githubusercontent.com/8338848/176181397-99c82d19-c8be-41eb-968b-d0a355fbbb37.png)

this is using blank branch parameter for all branches but also tried * and ** - same result

I see the the event from the webhook come in and be processed but pipeline does not activate

![image](https://user-images.githubusercontent.com/8338848/176181662-09239bfd-4c9a-48d0-8fc8-39425f2c3aaf.png)

I believe the trigger not set lines are from other jobs that dont have bpprp set .. the main pipeline build job does

currently trying to build a debugging version of plugin from source with increased level of log output but mvn package failing

any tips advice etc much appreciated

**Comment by jsj1027** [comment]
Im assuming from the pic you sent that this is not for a MultiBranchPipeline. If so, manually trigger a build of the pipeline and then try to have it trigger on Create or Update again.

**Comment by gmarzot** [comment]
that was in fact part of the issue .. this is a trigger only pipeline and was not set up for manual run . thank you for responding.
