### ISSUE TITLE
It only works if there is at least 1 build

### ISSUE THREAD

**Issue by x4team** [jenkinsci/bitbucket-push-and-pull-request-plugin#273]
I think this is a plugin bug.
For a long time I tried to understand why the assembly is not going, although polling is present in the logs. It turned out that if there are no successful builds in the job, then the build will not start.

Temporary solution: Manually run the first build for a new job

**Comment by y0zg** [comment]
it's not a plugin bug for sure but jenkins behavior in overall

**Comment by x4team** [comment]
> it's not a plugin bug for sure but jenkins behavior in overall

I think it is VERY important to specify this in the plugin description along with the lines in "Before you start"

**Comment by cdelmonte-zg** [comment]
@x4team are we talking about this? 

"The user initiliazes a new job starting manually a build."

See: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin#about-the-initialization-of-the-plugin

**Comment by y0zg** [comment]
whenever you use shared libraries or any git based job, first of all you need to run a job before its parameters  gets populated to UI. It's a common case if you have ever worked with jenkins, but reading a manual should help

**Comment by x4team** [comment]
> @x4team are we talking about this?
> 
> "The user initiliazes a new job starting manually a build."
> 
> See: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin#about-the-initialization-of-the-plugin

Yes, thanks. The information is listed at the very bottom of the page

**Comment by cdelmonte-zg** [comment]
@x4team feel free to submit a pull request if you'd like to change something in the readme and in the documentation :)
I'm closing this issue
