### ISSUE TITLE
[Feature] Approve pull request on successful build

### ISSUE THREAD

**Issue by chickenpie3** [jenkinsci/bitbucket-push-and-pull-request-plugin#29]
# Feature Request
Would it be possible to have the plugin approve the PR if the job is successful, and remove the approval if unsuccessful? 

# Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ x] There is no existing issue regarding the same topic
(i dont think so)

# Feature description
When job is successful, the Git user approves the PR
When job is unsuccessful, the Git user removes approval from the PR

# Possible Implementation
The bitbucket-pull-request-builder plugin does this.

**Comment by oviupstack** [comment]
Please add this feature, I'd love to use this plugin cause it is not doing polling regularly like the bitbucket-pull-request-builder plugin, however I really need the PR approval feature.

**Comment by atheros** [comment]
Yeah, without this feature, this plugin cannot replace bitbucket pull request builder
