### ISSUE TITLE
Webhook not triggering job

### ISSUE THREAD

**Issue by perezmark** [jenkinsci/bitbucket-push-and-pull-request-plugin#301]
In my repo
Repository hooks http://xxxxxx/bitbucket-hook/
with push enabled and pr approved

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/81707384/c882abc0-b2d7-477a-bcbc-93b739bf941c)

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/81707384/3a12672d-4063-45da-8ab0-557480302417)

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/81707384/332840f1-18c5-4662-ab11-a5c9801b6e74)

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/81707384/28790e1b-de2e-4f1d-af3c-ef046c6684f3)

plugin version: 2.8.3 
jenkins version: Jenkins 2.361.2

**Comment by cartsofware** [comment]
we also are facing the same issue 
the logs are the same as @alifiroozi80 
could someone help us please ?

**Comment by alifiroozi80** [comment]
Hello @cartsofware 
I managed to solve the problem.
I realized that I have the [BitBucket Plugin](https://plugins.jenkins.io/bitbucket) as well, and I installed the BitBucket Plugin during installation (Not from the Plugin Dashboard)
Somehow, they conflict with each other.
So, I deleted the BitBucket and BitBucket PR plugins completely, restarted Jenkins, and this time, installed both of them through Plugins dashboards (Not during installation)
And now both of them are working correctly.

---

P.S Note that if you want to keep both plugins, follow this [structure](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin#before-you-start):

**Comment by cartsofware** [comment]
hi @alifiroozi80 
thank you for your feedback. 
I installed only BB PR plugin and I have no log in jenkins log. So I remove everything and set a webhook in bitbucket using this format https://<user>:<token>@<jenkinsurl>/job/<jobname>/build 
so I don't need any plugin anymore

**Comment by alifiroozi80** [comment]
Hello @cartsofware 
They have released a version of plugin `3.0` a day ago.
I guess with that upgrade, it should work.

**Comment by julioc-p** [comment]
Hello @perezmark. Thanks for reporting!
Is what you shared the complete log?
