### ISSUE TITLE
Build status not being communicated to Bitbucket

### ISSUE THREAD

**Issue by cbolson1** [jenkinsci/bitbucket-push-and-pull-request-plugin#308]
I have a trigger setup, and Bitbucket is successfully triggering a job on Jenkins.  The problem is that the build status is not being relayed back to Bitbucket.

My job is setup as a pipeline job.  I don't see a spot where I can check a box to communicate build status notifications back to Bitbucket.

- Plugin version = 2.8.4
- Bitbucket server = 7.21.14

**Comment by cdelmonte-zg** [comment]
Hi @cbolson1 

you can find it in the System Configuration: Dashboard/Manage Jenkins/System

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/23214236/b8aca5e6-5634-498e-b4bc-e012c7cd319e)

**Comment by cbolson1** [comment]
Yep, I see it there.  Thanks!
