### ISSUE TITLE
"Single triggered job" option. How does it work?

### ISSUE THREAD

**Issue by x4team** [jenkinsci/bitbucket-push-and-pull-request-plugin#311]
Hi, everybody
In the 3.0 version of the plugin, the developers added the option "Single triggered job", which can be configured in Manage Jenkins -> System and it has only one field WITHOUT a DESCRIPTION of its work. Also in changelog I did not find a description of this option ((

I have several jobs, and some of them have several repositories with a web hook. I want only one (or a limited number) jobs to run with this web hook. Is this an option about this?
I tested this "Single triggered job" option and entered only my helm-upgrade job in this field. But unfortunately it didn't work, all jobs were started, where there was the same repository

**Comment by cdelmonte-zg** [comment]
@x4team  In the readme (Jenkins Global Configurations) there is a brief explanation of this new feature:

> you can configure a single job to be triggered exclusively. That overrides the default behavior of having a dedicated endpoint (+ some internal matching logic) for ALL pipelines to be triggered via this plugin. In case of a non-existing job a WARNING will be logged at global jenkins log. You can omit this feature by simply leaving this field blank.

**Comment by solarlodge** [comment]
hi @x4team :)
this feature is intended to one configure and ONLY one job to triggered via your configured hook endpoint.
the jobname needs to be the full path name. You can check this via your jenkins instance's groovy concsole via
`println Jenkins.instance.allItems.find { it.fullName.contains('PART_OF_YOUR_JOBNAME') }.fullName` e.g.
In case of a non-existing job there should be a warning in your jenkins log.

**Comment by x4team** [comment]
> hi @x4team :) this feature is intended to one configure and ONLY one job to triggered via your configured hook endpoint. the jobname needs to be the full path name. You can check this via your jenkins instance's groovy concsole via `println Jenkins.instance.allItems.find { it.fullName.contains('PART_OF_YOUR_JOBNAME') }.fullName` e.g. In case of a non-existing job there should be a warning in your jenkins log.

Hi @solarlodge , @cdelmonte-zg ,  thanks for the help
Via Jenkins.instance.AllItems.. I found joba's name as "Dev/Category/helm-upgrade",and inserted it into the settings of the Bitbucket PPR plugin (field "Single triggered job"). Next I pushed commit to "helm" repository, and I saw that not only the "helm-upgrade" job was launched, but also all the release ones

![Screenshot from 2023-10-31 15-31-01](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/16425058/23ec15a8-2230-45df-84c2-4b138a1403a4)

Are my actions correct?

**Comment by solarlodge** [comment]
@x4team Looks correct. Out of curiosity:
Does it work when you configure it, save and restart your whole jenkins instance AFTERWARDS?

**Comment by x4team** [comment]
> @x4team Looks correct. Out of curiosity: Does it work when you configure it, save and restart your whole jenkins instance AFTERWARDS?

YES, thanks. This solved my problem 🤝

**Comment by cdelmonte-zg** [comment]
More docus will be added in the next release of the plugin
