### ISSUE TITLE
[Request] Documentation on Bitbucket Cloud integration for build status propagation back to BB-cloud

### ISSUE THREAD

**Issue by samveen** [jenkinsci/bitbucket-push-and-pull-request-plugin#316]
The state of the union (between my Jenkins and BB-Cloud) is as below:
- I've got the push-pull plugin configured to build on PR creation in BB-cloud
- The credentials used to access BB-cloud are username/password.
- The plugin documentation lists username/password based status updates was dropped  by BB-cloud in 2022
- The sum total of the documentation on oauth for BB cloud updates is just link back to BB-Cloud docs.

Some documentation about the requirements and settings for the bb-push-pull-plugin to allow status push via oauth usage would be great, as the existing (lack of) documentation on this topic leads to newbies like me be getting stuck.

**Comment by ccecvb** [comment]
I'm also stuck on this. Created https://community.jenkins.io/t/bitbucket-push-and-pull-request-plugin-with-bitbucket-org-cloud-not-updating-pull-request/11813

**Comment by samveen** [comment]
Fixed by #324 , which has been merged. Closing.
