### ISSUE TITLE
bitbucket-push-and-pull-request-plugin stopped working with Bitbucket cloud

### ISSUE THREAD

**Issue by shahalam72** [jenkinsci/bitbucket-push-and-pull-request-plugin#320]
Hello,
bitbucket-push-and-pull-request-plugin not working with Bitbucket cloud.  
on Bitbucket Webhook we are getting the following HTTP 403 error:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
<table>
<tr><th>URI:</th><td>/bitbucket-ppr-webhook</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 10.0.15</a><hr/>

</body>
</html>

========== Versions =========

Jenkins: 2.414.2
bitbucket-push-and-pull-request-plugin: 3.0.1
Bitbucket Plugin: 241.v6d24a_57f9359

We removed "Bitbucket Plugin" and only had bitbucket-push-and-pull-request-plugin, but that still gets the same error.
We tried createing  a new PR webhook "https://buildpp.pacelabs.com:8443/bitbucket-ppr-webhook", which is separate from default webhook "https://buildpp.pacelabs.com:8443/bitbucket-hook/", but still get 403 error for PR webhook.

I will appreciate your quick response on this issue.

Thanks,
Shah Alam

**Comment by shahalam72** [comment]
Hello,
  I will appreciate an update on this issue.  One of our developer found that mongo shell for v6 wasn't installed right, so he reinstalled it using following commands.  
dnf erase -qy mongodb-mongosh
dnf install -qy mongodb-mongosh-shared-openssl3

We are not seeing 403 error in Bitbucket Webhook after that for PR, but PR build still not getting triggered Jenkins.

Thank you.

**Comment by cdelmonte-zg** [comment]
Hallo @shahalam72, 

As I read, you are not having problems with the 443 anymore, and the issue is now that the job, where you configured the plugin, is not being triggered as a pull request is coming in.

I have 2questions:

 - Did the plugin already work in the past or is it the first time you are using it?
 - Did you trigger manually the Jenkins job for its first time execution? That’s necessary to use the plugin with pipeline jobs
 
May you provide logs of the plugin, after removing eventual sensitive information. 
 
Thanks

**Comment by malikdaman24** [comment]
I am alss facing similar issue. Getting 200 from the bitbucket cloud but jenkins job is not getting triggered

**Comment by malikdaman24** [comment]
I am getting below error. Is this because bitbucket plugin is also installed?
"java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Expected 1 instance of io.jenkins.plugins.bitbucketpushandpullrequest.config.BitBucketPPRPluginConfig but got 2 [in thread "Handling POST /bitbucket-ppr-webhook/ from XXXXXXXXX : Jetty (winstone)-173"]"

**Comment by shahalam72** [comment]
Hello,
apologize for delayed response.  As you can see in attached image  the webhook has return code 200, but nothing happens on Jenkins Server (log attached).  I did trigger the Jenkins job manually when it was created. 

![web
[jenkins.log](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/files/13834425/jenkins.log)
hook](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/45405188/6a21d84e-35ae-4b80-9caa-0b455cd851e0)

**Comment by shahalam72** [comment]
[jenkins.log](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/files/13834440/jenkins.log)

**Comment by cdelmonte-zg** [comment]
Hallo @shahalam72 


From the log I cannot find any errors related to the plugin, it seems to me that the Job was triggered. See following:

ˋˋˋ
2023-07-25 21:39:25.050+0000 [id=225]	INFO	c.c.j.p.BitBucketTriggerRunnable#buildJob: SCM changes detected in [build-dev]. Triggering [ #12]
2023-07-25 21:39:34.435+0000 [id=250]	INFO	o.j.p.b.BitbucketBuildStatusNotifierStep$Execution#run: Got commit id null
2023-07-25 21:39:34.435+0000 [id=250]	INFO	o.j.p.b.BitbucketBuildStatusNotifierStep$Execution#run: Got repo slug = null
2023-07-25 21:39:34.939+0000 [id=250]	INFO	o.j.p.b.BitbucketBuildStatusHelper#sendBuildStatusNotification: This request was sent: {
  "state": "INPROGRESS",
  "key": "c963ed106f1c29f4589c7dff8288c7f2",
  "url": "https://jenkins_server:8443/job/b2bservices/job/build-dev/12/display/redirect",
  "name": "b2bservices/build-dev #12"
}

(…)

2023-07-25 21:39:46.446+0000 [id=250]	INFO	o.j.p.b.BitbucketBuildStatusHelper#sendBuildStatusNotification: This request was sent: {
  "state": "SUCCESSFUL",
  "key": "c963ed106f1c29f4589c7dff8288c7f2",
  "url": "https://jenkins_server:8443/job/b2bservices/job/build-dev/12/display/redirect",
  "name": "b2bservices/build-dev #12"
}
ˋˋˋ
May you send the logs only for this specific plugin to the finest Level? Maybe there can be found more…
