### ISSUE TITLE
what is the issue  am getting "trigger not set"

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [jenkinsci/bitbucket-push-and-pull-request-plugin#332]
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.observer.BitBucketPPRObserverFactory
Add BitBucketPPRPullRequestCloudObserver for {}
May 27, 2024 4:20:28 PM INFO io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPayloadProcessorFactory createProcessor
Create BitBucketPPRPullRequestCloudPayloadProcessor
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
itona_ci SCM doesnt match remote repo {1} or it was already triggered.
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set
May 27, 2024 4:20:28 PM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Trigger not set

**Comment by cdelmonte-zg** [comment]
Hello @MohamedKHALILRouissi 

if the issue is still relevant, feel free to reopen it, adding more context 

Tnx
