### ISSUE TITLE
Add examples to help / readme

### ISSUE THREAD

**Issue by PhilippDehner** [jenkinsci/bitbucket-push-and-pull-request-plugin#337]
I'd like to use the triggers in my declarative pipeline script. I couldn't find any solutions in the internet, so maybe it would be nice to add it to the readme of the plugin.

My problem is: 
I’d like to trigger my pipeline after opening and updating a pull request in bitbucket.
If I do the following, I get an error:

```pipeline {
  triggers {
    bitBucketTrigger([
      pullRequestServerCreatedAction(allowedBranches: 'origin/(.*)', isToApprove: true),
      pullRequestServerUpdatedAction(allowedBranches: 'origin/(.*)', isToApprove: true)
    ])
  }
  stages {
    ...
  }
}
```

The error was:
`org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: ae121c1a-49a4-4ced-b330-a6e7130dd5fb
java.lang.NoSuchMethodError: No such DSL method 'pullRequestServerCreatedAction' found among steps`

**Comment by PhilippDehner** [comment]
> Hi! You can take a look at testDslTriggerCreateUpdatedMergedApprovedPRAllowBranchesWithApproveActionsPipeline.groovy in the test.resources.dsl . You can find a lot of examples for many use cases in this resources folder as well

Thanks for your replay. In my case I use declarative pipeline scripts. I did not find any documentation how to integrate the [properties](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/bcc10b88b37107249831dfd083ece80194704b41/src/test/resources/dsl/testDslTriggerCreateUpdatedMergedApprovedPRAllowBranchesWithApproveActionsPipeline.groovy#L2) into my script...

**Comment by julioc-p** [comment]
Here is an example you can take a look at in the Readme: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin#pipeline-script. Should be more specific to your case
