### ISSUE TITLE
WARNING: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1550 path $.repository.links.self"

### ISSUE THREAD

**Issue by dlapanik** [jenkinsci/bitbucket-push-and-pull-request-plugin#35]
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There is no existing issue regarding the same topic

* Plugin Version: 1.62
* Jenkins Version: 2.164.3
* Jenkins Job Type: Pipline
* Triggered via: Bitbucket Server 5.15.3 with bitbucket-webhooks 1.6.3

# Expected Behavior
Payload handled correctly

# Actual Behavior
Waning in logs saying "WARNING: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1550 path $.repository.links.self"

# Possible Solution
Not obligatory, but suggest a fix/reason for the bug

# Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug
1.
1.
1.
1.

# Context
How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world.

## Bitbucket payload
Only if relevant, will be helpful for reproducing the issue

## Jenkins Job configuration
Only if relevant. Mainly scm and plugin parts will be helpful for reproducing the issue

## Jenkins logs
Only if relevant, will be helpful for debugging

**Comment by cdelmonte-zg** [comment]
Hi @dlapanik , the plugin doesn't support bitbucket-webhooks anymore. You need to use the webhooks provided directly by the Bitbucket Server. 
[Managing webhooks in Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html) describes how to configure them.

Actually only the push trigger is supported, we are going to add the support for pull request in the next releases.

**Comment by dlapanik** [comment]
Hi @cdelmonte-zg,

it is not working as well.
Bit bucket sends 'opened' event type, while you expect 'created', same for "modified" vs "updated".

Denis.

**Comment by cdelmonte-zg** [comment]
Hi @dlapanik, 
might you attach the payload, after removing from it sensitive informations?
Thank you

Christian

**Comment by dlapanik** [comment]
@cdelmonte-zg i can do it a bit later,
but even in documentation [Managing webhooks in Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html) following wording is used:
 Pull request events

    Opened
    Approved
    Unapproved
    Needs work
    Merged
    Declined
    Deleted
    Comment added
    Comment edited
    Comment deleted

Denis

**Comment by cdelmonte-zg** [comment]
Hi  @dlapanik, 

if I understand well, these words, you listed above, are the 'labels' used to describe the events that trigger a given behavior. In the payload sent by the official bitbucket server webhook, these 'labels' are translated in specific tags, for example push is translated in 'repo:refs_changed'. 
This plugin uses these tags to identify  which kind of event want to trigger a job (That's also the reason, why we need the payload to try to understand what's going wrong).

You can find more about this topic consulting this resource: [Event payload]
(https://confluence.atlassian.com/bitbucketserver0514/using-bitbucket-server/managing-webhooks-in-bitbucket-server/event-payload).

If I misunderstood something in your comments, please let me know :)
Chr

**Comment by dlapanik** [comment]
@cdelmonte-zg 
This is workload:
{
	"eventKey": "pr:modified",
	"date": "2019-05-27T09:51:31+0000",
	"actor": {
		"name": "admin",
		"emailAddress": "myemail@mail.com",
		"id": 1,
		"displayName": "admin",
		"active": true,
		"slug": "admin",
		"type": "NORMAL",
		"links": {
			"self": [{
					"href": "http://mybbucket/users/admin"
				}
			]
		}
	},
	"pullRequest": {
		"id": 1,
		"version": 4,
		"title": "pr title",
		"description": "dens enis",
		"state": "OPEN",
		"open": true,
		"closed": false,
		"createdDate": 1558538456543,
		"updatedDate": 1558950691633,
		"fromRef": {
			"id": "refs/heads/spacedogs-branchName",
			"displayId": "spacedogs-branchName",
			"latestCommit": "e2a0224bb79cbe95635638524e166ac61b6f99c3",
			"repository": {
				"slug": "repo-name",
				"id": 2,
				"name": "repo-name",
				"scmId": "git",
				"state": "AVAILABLE",
				"statusMessage": "Available",
				"forkable": true,
				"project": {
					"key": "PR01",
					"id": 1,
					"name": "Project 01",
					"public": false,
					"type": "NORMAL",
					"links": {
						"self": [{
								"href": "http://mybbucket/projects/PR01"
							}
						]
					}
				},
				"public": false,
				"links": {
					"clone": [{
							"href": "http://mybbucket/scm/PR01/repo-name.git",
							"name": "http"
						}, {
							"href": "ssh://git@mybbucket:7999/PR01/repo-name.git",
							"name": "ssh"
						}
					],
					"self": [{
							"href": "http://mybbucket/projects/PR01/repos/repo-name/browse"
						}
					]
				}
			}
		},
		"toRef": {
			"id": "refs/heads/branchName",
			"displayId": "branchName",
			"latestCommit": "a52926533e7b60027de93fd539e95d32f4ad8346",
			"repository": {
				"slug": "repo-name",
				"id": 2,
				"name": "repo-name",
				"scmId": "git",
				"state": "AVAILABLE",
				"statusMessage": "Available",
				"forkable": true,
				"project": {
					"key": "PR01",
					"id": 1,
					"name": "Project 01",
					"public": false,
					"type": "NORMAL",
					"links": {
						"self": [{
								"href": "http://mybbucket/projects/PR01"
							}
						]
					}
				},
				"public": false,
				"links": {
					"clone": [{
							"href": "http://mybbucket/scm/PR01/repo-name.git",
							"name": "http"
						}, {
							"href": "ssh://git@mybbucket:7999/PR01/repo-name.git",
							"name": "ssh"
						}
					],
					"self": [{
							"href": "http://mybbucket/projects/PR01/repos/repo-name/browse"
						}
					]
				}
			}
		},
		"locked": false,
		"author": {
			"user": {
				"name": "admin",
				"emailAddress": "myemail@mail.com",
				"id": 1,
				"displayName": "admin",
				"active": true,
				"slug": "admin",
				"type": "NORMAL",
				"links": {
					"self": [{
							"href": "http://mybbucket/users/admin"
						}
					]
				}
			},
			"role": "AUTHOR",
			"approved": false,
			"status": "UNAPPROVED"
		},
		"reviewers": [],
		"participants": [],
		"links": {
			"self": [{
					"href": "http://mybbucket/projects/PR01/repos/repo-name/pull-requests/1"
				}
			]
		}
	},
	"previousTitle": "Pr CommentS",
	"previousDescription": "descr sdfsd fsd",
	"previousTarget": {
		"id": "refs/heads/branchName",
		"displayId": "branchName",
		"type": "BRANCH",
		"latestCommit": "a52926533e7b60027de93fd539e95d32f4ad8346",
		"latestChangeset": "a52926533e7b60027de93fd539e95d32f4ad8346"
	}
}

This is in Jenkins console:
May 27, 2019 9:51:31 AM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
INFO: Received x-event-key payload from bitbucket
May 27, 2019 9:51:31 AM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
WARNING: The eventAction pr  modified is not supported.
May 27, 2019 9:51:31 AM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
INFO: Sending response.
May 27, 2019 9:51:31 AM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
INFO: Response sent.

**Comment by cdelmonte-zg** [comment]
Hi @dlapanik,

thank you! As you can see from the "eventKey": "pr:modified", this is the payload generated for a modified pull request. Actually this plugin supports only the push event of the Bitbucket Server. 
Could you send a push event payload? It is the one with the event key "repo:refs_changed'.

Thanks, 
Chr
