### ISSUE TITLE
BITBUCKET_SOURCE_BRANCH has wrong value for repo:push events

### ISSUE THREAD

**Issue by gmarzot** [jenkinsci/bitbucket-push-and-pull-request-plugin#38]
* Plugin Version: 1.6.2
* Jenkins Version: 2.164.2
* Jenkins Job Type: Freestyle job, and Pipeline
* Triggered via: Bitbucket Cloud repo:push event to master

# Expected Behavior
As per the docs, BITBUCKET_SOURCE_BRANCH is expected to have a branch name for both pull and push events.

# Actual Behavior
for repo:push event this value appears to be the repository name

# Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug
1. setup a push webhook in BitBucket
2. set up SCM in jenkins job for repo and branch '*/master'
3. setup job build trigger for "Push" event, allowed branches: '*/master'
4. merge code change to master and observe value of BITBUCKET_SOURCE_BRANCH

# Context
it is useful for this environment variable to have a similar role for push and pull events to avoid special case code.

**Comment by cdelmonte-zg** [comment]
Hello @gmarzot 

please test it with the release 1.6.3

Thank you

**Comment by gmarzot** [comment]
hello - this appears to be fixed in 1.6.3. thank you.
