### ISSUE TITLE
repo:push to master events do not trigger builds

### ISSUE THREAD

**Issue by gmarzot** [jenkinsci/bitbucket-push-and-pull-request-plugin#39]
* Plugin Version: 1.6.2
* Jenkins Version: 2.164.2
* Jenkins Job Type: Pipeline
* Triggered via: Bitbucket Cloud repo:push

# Expected Behavior
When a BitBucket webhook for repo:push is configured and sent to Jenkins/plugin a build is triggered for resulting merged master branch

# Actual Behavior
No build is triggered because the test for hasChanges() returns no significant changes

# Possible Solution
find a way to populate the changes for the push action object

# Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug
1. setup BitBucket webhook for repo:push events
2. setup jenkins scm for repo and branch '*/master'
3. setup build trigger for plugin "Push" allowed branches '*/master'
4.merge code to master

# Context
need to notice changes to master and trigger builds

## Jenkins logs
INFO: Should schedule job : true and (polling result has changes false or is pull request false)

**Comment by cdelmonte-zg** [comment]
Might you provide more context?
Thanks

**Comment by gmarzot** [comment]
not sure what additional info is needed. I ended up hacking the code to get it to work for us.
diff attached. I was not able to fully inspect the changes tracked by the event in the plugin code.. but it appeared to consider them "INSIGNIFICANT" despite the event being caused by a substantive merge/push to origin/master

I dont think my code change is correct but am not sure how this plugin determines the 'changes' metric from the bitbucket webhook payload.

[repo_push_diff.txt](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/files/3306553/repo_push_diff.txt)

**Comment by cdelmonte-zg** [comment]
Hi @gmarzot, 
I'll check the diff, thank you for sharing it.

One question, did you try to configure the push allowed branches simply with 'master' instead than '*/master'? 

There were some changes in the plugin to allow regex etc. in the style of the git plugin and the screenshot in the documentation was updated only today...

**Comment by gmarzot** [comment]
I believe we tried it both ways... but it looked like the allowed branch test was passing fine.

that line was coming back false
     boolean hasChanges = pollingResult.hasChanges();

I don't know why pollingResult is in the picture at all.. isn't all the necessary info in the webhook payload?

**Comment by cdelmonte-zg** [comment]
Hi @gmarzot, pollingResult.hasChanges() method isn't part of the plugin, but it's coming from [here](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/scm/PollingResult.java)

We are using it on the push events,  to be sure, that we are triggering a job only in case of a change in the related repository.

To be sure that changes between remote and local branch exist, you could check the diffs between the pertinent remote branch on the bitbucket cloud server and the correlated local branch on the Jenkins server using `git status` or something similar from the shell of the server where Jenkins is running on...

Let me know

**Comment by cdelmonte-zg** [comment]
@gmarzot do you have some news? The version 2 of the plugin was released yesterday, maybe is the problem solved in the new version?

**Comment by arohithr8** [comment]
Hi I'm facing same issue but for feature branches repo:push to feature events do not trigger builds.

Can you help on how to solve it. 

Plugin-Version: 2.0.0
Jenkins-Version: 2.176.1

jenkins log:

Should schedule job : true and (polling result has changes **false** or is pull request false)


It's working fine for Master and PR.

**Comment by vweng** [comment]
We're facing exactly same issue. Please remove the **pollingResult.hasChanges()** check, as it always return **false** with feature branch pushes. It's working fine for master and PR though.

Plugin-Version: 2.0.0
Jenkins-Version: 2.190.1

**Comment by vweng** [comment]
So this is same bug as https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/54

**Comment by cdelmonte-zg** [comment]
@vweng @arohithr8 please, can you test the bitbucket-push-and-pull-request-2.1.0-beta-3  version and let me know if it works for you? Thank you

**Comment by vweng** [comment]
Just tested with the latest 2.2.0. Same issue. In order get it working, I have to replace line #359 in */src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRTrigger.java*
from 
`&& (pollingResult.hasChanges() || filter.shouldTriggerAlsoIfNothingChanged());`
to
`&& (filter.shouldTriggerAlsoIfNothingChanged());`

Basically the pollingResult.hasChanges() logic always returns true if the pipeline scm is set to build wildcard branches with branch/name set to `feat/**`. It does work if the branch name is set to a specific one, like `master`. However, wildcard match is something we can't forego.

**Comment by vweng** [comment]
@cdelmonte-zg Thanks for adding the triggerAlsoIfNothingChanged option, I can confirm it works with the following settings:

`bitBucketTrigger([[$class: 'BitBucketPPRRepositoryTriggerFilter', 
							actionFilter: [$class: 'BitBucketPPRRepositoryPushActionFilter', 
								triggerAlsoIfNothingChanged: true, 
								triggerAlsoIfTagPush: false]]])`

**Comment by arohithr8** [comment]
@cdelmonte-zg Thank you, after updating to version 2.2  and adding **triggerAlsoIfNothingChanged: true** as @vweng mentioned above it's working as expected.

**Comment by cdelmonte-zg** [comment]
Thank you all, I updated just now the readme file.
