### ISSUE TITLE
Triggers builds for unwanted branches on Jenkins

### ISSUE THREAD

**Issue by raghav-a** [jenkinsci/bitbucket-push-and-pull-request-plugin#40]
* Plugin Version: 1.6.2
* Jenkins Version: 2.153
<img width="1049" alt="Screen Shot 2019-06-11 at 3 01 11 pm" src="https://user-images.githubusercontent.com/2734980/59333416-e5c17000-8d15-11e9-8594-d44c106c123b.png">

* Jenkins Job Type: multibranch pipeline
* Triggered via: Bitbucket Cloud 

# Expected Behavior
This plugin should trigger the build only for the specific branch for which the pull request has been created / updated 

# Actual Behavior
When a pull request is updated / created it ends up triggering build for many branches

**Comment by cdelmonte-zg** [comment]
Hi @raghav-a ,

thank you for your feedback,
We will add this feature in one of the next releases. Stay tuned!  :)

**Comment by raghav-a** [comment]
for now i was able to get it working for my use case by adding some code in BitBucketPPRJobProbe class. Would wait for your next release

To make it work for all types of pipelines, we will have to add a conditional code isPipelineMultibranch just above the code i added 



`package io.jenkins.plugins.bitbucketpushandpullrequest;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.eclipse.jgit.transport.RemoteConfig;
import org.eclipse.jgit.transport.URIish;

import com.google.common.base.Objects;

import hudson.model.Job;
import hudson.plugins.git.GitSCM;
import hudson.plugins.git.GitStatus;
import hudson.plugins.mercurial.MercurialSCM;
import hudson.scm.SCM;
import hudson.security.ACL;
import hudson.security.ACLContext;
import io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRAction;
import io.jenkins.plugins.bitbucketpushandpullrequest.model.cloud.BitBucketPPREvent;
import jenkins.model.Jenkins;
import jenkins.model.ParameterizedJobMixIn;
import jenkins.model.ParameterizedJobMixIn.ParameterizedJob;
import jenkins.triggers.SCMTriggerItem;


public class BitBucketPPRJobProbe {
  private static final Logger LOGGER = Logger.getLogger(BitBucketPPRJobProbe.class.getName());
  private BitBucketPPREvent bitbucketEvent;
  private BitBucketPPRAction bitbucketAction;

  public void triggerMatchingJobs(BitBucketPPREvent bitbucketEvent,
      BitBucketPPRAction bitbucketAction) {
    this.bitbucketEvent = bitbucketEvent;
    this.bitbucketAction = bitbucketAction;

    if (!("git".equals(bitbucketAction.getScm()) || "hg".equals(bitbucketAction.getScm()))) {
      throw new UnsupportedOperationException("Unsupported SCM type " + bitbucketAction.getScm());
    }

    // TODO: do we need it?
    Jenkins.get().getACL();

    try (ACLContext old = ACL.as(ACL.SYSTEM) ) {
      List<URIish> remotes = getRemotesAsList(bitbucketAction);
      LOGGER.log(Level.FINE, "Considering remote {0}", remotes);

      Jenkins.get().getAllItems(Job.class).stream().forEach(job -> {
        LOGGER.log(Level.FINE, "Considering candidate job {0}", job.getName());

        triggerScm(job, remotes, bitbucketAction);
      });
    } catch (Exception e) {
      LOGGER.log(Level.WARNING, "Invalid repository URLs {0}\n{1}",
          new Object[] {bitbucketAction.getScmUrls(), e.getMessage()});
    }
  }

  List<URIish> getRemotesAsList(BitBucketPPRAction bitbucketAction) {
    return (List<URIish>) (bitbucketAction.getScmUrls()).stream().map(a -> {
      try {
        return new URIish(a);
      } catch (URISyntaxException e) {
        LOGGER.log(Level.WARNING, "Invalid URI {0}", e.getMessage());
        return null;
      }
    }).collect(Collectors.toList());
  }

  void triggerScm(Job<?, ?> job, List<URIish> remotes, BitBucketPPRAction bitbucketAction) {
    LOGGER.log(Level.FINE, "Considering to poke {0}", job.getFullDisplayName());
    Optional<BitBucketPPRTrigger> bitbucketTrigger = getBitBucketTrigger(job);
    List<SCM> scmTriggered = new ArrayList<>();
    Optional<SCMTriggerItem> item =
        Optional.ofNullable(SCMTriggerItem.SCMTriggerItems.asSCMTriggerItem(job));

    bitbucketTrigger
        .ifPresent(trigger -> item.ifPresent(i -> i.getSCMs().stream().forEach(scmTrigger ->
        {

          if(!isPrSourceBranchSameAsJobsBranch(job, bitbucketAction)){
            LOGGER.info("Skipping for job:"+job.getDisplayName());
            return;
          }

          LOGGER.info("Scheduling for job:"+job.getDisplayName());

          boolean isRemoteSet = false;
          for (URIish remote : remotes) {
            if (match(scmTrigger, remote)) {
              isRemoteSet = true;
              break;
            }
          }

          if (isRemoteSet && !hasBeenTriggered(scmTriggered, scmTrigger)) {
            scmTriggered.add(scmTrigger);
            LOGGER.log(Level.FINE, "Triggering trigger {0} for job {1}",
                new Object[] {trigger.getClass().getName(), job.getFullDisplayName()});
            try {
              trigger.onPost(bitbucketEvent, this.bitbucketAction);
            } catch (Exception e) {
              LOGGER.log(Level.WARNING, "Error: {0}", e.getMessage());
            }
          } else {
            LOGGER.log(Level.FINE, "{0} SCM doesn't match remote repo {1}",
                new Object[] {job.getName(), remotes});
          }
        })));
  }

  private boolean isPrSourceBranchSameAsJobsBranch(Job<?, ?> job, BitBucketPPRAction bitbucketAction) {
    final String displayName = job.getDisplayName();
    final String fullDisplayName = job.getFullDisplayName();
    final String sourceBranchName = bitbucketAction
        .getPayload()
        .getPullRequest()
        .getSource()
        .getBranch()
        .getName();
    LOGGER.info("Job Details : " +job.toString());
    LOGGER.info("Job Name : " +displayName);
    LOGGER.info("Job full Name : " +fullDisplayName);
    LOGGER.info("sourceBranchName : " +sourceBranchName);
    LOGGER.info("bitbucket a" +
        "ction details" + bitbucketAction.getPayload());

    return displayName.equals(sourceBranchName);
  }

  private Optional<BitBucketPPRTrigger> getBitBucketTrigger(Job<?, ?> job) {
    if (job instanceof ParameterizedJobMixIn.ParameterizedJob) {
      ParameterizedJobMixIn.ParameterizedJob<?, ?> pJob =
          (ParameterizedJobMixIn.ParameterizedJob<?, ?>) job;

      return getBitBucketTrigger(pJob);
    }

    return Optional.empty();
  }

  private Optional<BitBucketPPRTrigger> getBitBucketTrigger(ParameterizedJob<?, ?> job) {
    return job.getTriggers().values().stream().filter(e -> e instanceof BitBucketPPRTrigger)
        .findFirst().map(p -> (BitBucketPPRTrigger) p);
  }

  private boolean hasBeenTriggered(List<SCM> scmTriggered, SCM scmTrigger) {
    for (SCM scm : scmTriggered) {
      if (scm.equals(scmTrigger)) {
        LOGGER.log(Level.FINEST, "Has been triggered {0}", scmTrigger.getType());
        return true;
      }
    }

    return false;
  }

  private boolean match(SCM scm, URIish url) {
    if (scm instanceof GitSCM) {
      return matchGitScm(scm, url);
    } else if (scm instanceof MercurialSCM) {
      return matchMercurialScm(scm, url);
    }

    return false;
  }

  private boolean matchMercurialScm(SCM scm, URIish remote) {
    try {
      URI hgUri = new URI(((MercurialSCM) scm).getSource());

      LOGGER.log(Level.INFO, "Trying to match {0} ", hgUri.toString() + "<-->" + remote.toString());
      if (looselyMatches(hgUri, remote)) {
        LOGGER.info("Machted scm");
        return true;
      }
    } catch (URISyntaxException ex) {
      LOGGER.log(Level.SEVERE, "Could not parse jobSource uri: {0} ", ex);
    }

    return false;
  }

  private boolean matchGitScm(SCM scm, URIish remote) {
    for (RemoteConfig remoteConfig : ((GitSCM) scm).getRepositories()) {
      for (URIish urIish : remoteConfig.getURIs()) {
        LOGGER.log(Level.INFO, "Trying to match {0} ",
            urIish.toString() + "<-->" + remote.toString());
        if (GitStatus.looselyMatches(urIish, remote)) {
          LOGGER.info("Machted scm");
          return true;
        }
      }
    }

    return false;
  }

  // needed cause the ssh and https URI differs in Bitbucket Server.
  @Deprecated
  private URIish parseBitBucketUrIish(URIish urIish) {
    if (urIish.getPath().startsWith("/scm")) {
      urIish = urIish.setPath(urIish.getPath().substring(4));
    }
    return urIish;
  }

  private boolean looselyMatches(URI notifyUri, URIish repository) {
    boolean result = false;
    try {
      URI repositoryUri = new URI(repository.toString());
      result = Objects.equal(notifyUri.getHost(), repositoryUri.getHost())
          && Objects.equal(notifyUri.getPath(), repositoryUri.getPath())
          && Objects.equal(notifyUri.getQuery(), repositoryUri.getQuery());
    } catch (URISyntaxException ex) {
      LOGGER.log(Level.SEVERE, "Could not parse repository uri: {0}, {1}",
          new Object[] {repository, ex});
    }

    return result;
  }
}
`

**Comment by raghav-a** [comment]
Hi @cdelmonte-zg,

Thanks for your response.
For now, I could get it working for my usecase my making some changes in class BitBucketPPRJobProbe .
here is the pull request https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/43

Waiting for your next release!!

**Comment by kaplanitay** [comment]
Having the same issue.
How can I trigger a build only for the pulled requested branch?

Thanks

**Comment by raghav-a** [comment]
@kaplanitay i have created a pull request which fixes issue for multibranch pipeline - https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/43

you can build the plugin from here 
https://github.com/raghav-a/bitbucket-push-and-pull-request-plugin/tree/multiBranchPipelineFix and deploy it in jenkins

**Comment by cdelmonte-zg** [comment]
@raghav-a, I tested your pull request but something is breaking the pipeline and freestyle jobs. I will work on it in the next days. In the meanwhile, can you update your fork to the newest plugin version 2.0.0, just to check if all in your fork is still working as expected from you?
Thank you

**Comment by raghav-a** [comment]
@cdelmonte-zg 

I added a todo in BitBucketPPRJobProbe for the same..
Basically we need to check if the Job is multibranch pipeline then only execute the code i wrote.
If you can share the code for how to check if the Job is multibranch, i can update the pull request to fix the issues for pipeline and freestyle jobs

**Comment by jchristheodore** [comment]
Can we please do this branch filtering for all jobs?

**Comment by krezzoid** [comment]
hi @cdelmonte-zg 
do you have any updates for this PR?

**Comment by mamkkl** [comment]
@cdelmonte-zg hi, any updates?

**Comment by cdelmonte-zg** [comment]
Hi, we added the pull request. can you please test the bitbucket-push-and-pull-request-2.1.0-beta-1 release? Thank you!
Christian

**Comment by raghav-a** [comment]
Hi @cdelmonte-zg,
I have tested this beta.. looks good. When will this be released?
Thanks
raghav

**Comment by raghav-a** [comment]
Hi @cdelmonte-zg 

There seems to be some issue in bitbucket-push-and-pull-request-2.1.0-beta-1 for pipeline jobs. Multibranch seems to be fine. However i tested with bitbucket-push-and-pull-request-2.1.0-beta-2-SNAPSHOT by building it locally that works. 

When will you release this?

**Comment by cdelmonte-zg** [comment]
Hi @raghav-a,
thank you for the feedback! 
I'm going to do a second beta release today and hopefully this will work.
To release the plugin we must be sure that all is working as expected for all the job types...

May you send me a jenkinsfile example for the multibranch pipeline job? Tnx

**Comment by cdelmonte-zg** [comment]
Hi @raghav-a 

can you confirm if the beta-2 is working for you?
bitbucket-push-and-pull-request-2.1.0-beta-2

Thanks

**Comment by raghav-a** [comment]
Hi @cdelmonte-zg 

The beta is working for me. However there was another issue with this feature.
What ideally should happen is 
when (event is merged)
      trigger target branch
else
      trigger source branch

i have implemented the same and raised the pull request - https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/pull/59

Please have a look at it.
Thanks

**Comment by jchristheodore** [comment]
Hi @cdelmonte-zg 

Does the branch filtering work for free style jobs as well with the new plugin version 2.2.0?

**Comment by cdelmonte-zg** [comment]
hi @jchristheodore 

you can already set filters on the branch names for freestyle and "single" pipeline jobs triggered by push events.
Or do you mean something else?

**Comment by jchristheodore** [comment]
@cdelmonte-zg 

Yup. I meant the filtering on branch names for Pull Request Created, Approved & Updated as well. Is there a plan to include those as part of this enhancement?

**Comment by cdelmonte-zg** [comment]
@jchristheodore

okay, I'll include in the next minor release :+1:
Can you create a new issue for that?
Thank you

**Comment by jchristheodore** [comment]
@cdelmonte-zg 

Sure. Thanks. #61

**Comment by macghriogair** [comment]
closing this as @raghav-a original issue seems to be fixed with PR #59
