### ISSUE TITLE
Branch expression matching before triggering the build: expecting fix for Bitbucket server

### ISSUE THREAD

**Issue by grantsunny** [jenkinsci/bitbucket-push-and-pull-request-plugin#44]
Hi @cdelmonte-zg and @macghriogair

I were very happy to see changes fixing issue #36 so I downloaded this upgrade and made a try. However, it seems my build is not being triggered. After checking the content of the commit, I found this PR seems fixed the issue on Bitbucket Cloud, but may forget to make changes for Bitbucket server which is supposed to be taken care of in BitBucketPPRServerRepositoryPushActionFilter, am I right? I am keeping my local changes for a while. :-)

Anyway, thank you so much for your attention and appreciate your great help! 
Regards, 
Grant.

**Comment by cdelmonte-zg** [comment]
Hi @grantsunny, thank you!

With the release 1.6.4 we should have all at its place :)

**Comment by grantsunny** [comment]
Everything works great! Appreciate your great work guys!

**Comment by cdelmonte-zg** [comment]
Thank you!
