### ISSUE TITLE
An exception appears on pull request: ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

### ISSUE THREAD

**Issue by D1987** [jenkinsci/bitbucket-push-and-pull-request-plugin#52]
# Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [ ] There is no existing issue regarding the same topic

* Plugin Version: 2.0.0
* Jenkins Version: 2.183
* Jenkins Job Type: Pipeline
* Triggered via: Bitbucket Cloud

# Expected Behavior
Success build

# Actual Behavior
I get an exception: ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

# Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug
1. Create pipeline
2. Add pull request trigger (created)

# Context
We have several jobs for unit tests (.net core/angular)
It exception appears sometimes but if it happens next build won't start, only after manually start

## Jenkins Job configuration
**section Build triggers:**
check _Build with BitBucket Push and Pull Request Plugin_ with  _BitBucket cloud pull request = created_
**section Pipeline script:**
```
 stage('Checkout') {
            steps {             
              git credentialsId: 'my cred', url: 'my url', branch: '${BITBUCKET_SOURCE_BRANCH}'
            }
        }
```

**Comment by cdelmonte-zg** [comment]
Hi @D1987 

do you still have this issue with the new release?

**Comment by rirl** [comment]
As of 01/15/2020 and the latest edition of everything related, we see still see this problem.

**Comment by cdelmonte-zg** [comment]
@rirl  if you send a log of a failing job, it would be helpful. Please, in this case, remove before posting it all sensitive information. Thanks

**Comment by macghriogair** [comment]
Not sure if it was the cause, but maybe it helps: Could it be caused by force pushes to the repo/branch? The original error indicates that the revision does no longer exist in the repo. This frequently happens with git force pushes re-writing history.
