### ISSUE TITLE
DSL pipeline, allowedBranches to be parametric

### ISSUE THREAD

**Issue by VassilMarjunits** [jenkinsci/bitbucket-push-and-pull-request-plugin#53]
# Feature Request
Sorry if im not servin this issue properly.
Im looking for option to be **allowedBranches to be parametric** in DSL pipeline
We have jobs witch is related to the branches, but Jenkinsfile is only one in all branches

# Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ x] There is no existing issue regarding the same topic

# Feature description
Jenkins ver. 2.176.1
Plugin Version: 2.0.0
Jenkins Version: 2.176.1
Jenkins Job Type: Pipeline
Triggered via: Bitbucket Server

`pipeline {
  agent any
  environment {
  	BRANCH="${env.GIT_BRANCH}"
  }
  triggers {
	 bitBucketTrigger([[$class: 'BitBucketPPRRepositoryTriggerFilter', actionFilter: [$class: 'BitBucketPPRServerRepositoryPushActionFilter', allowedBranches: "${BRANCH}", triggerAlsoIfTagPush: false]]])
  }

  stages {
    stage('Webhook test') {
      steps {
        echo "${env.GIT_BRANCH}"
        echo "${BRANCH}"
        echo "${env.JOB_NAME}"
      }
    }
  }
}`

Jenkins shows an exception: 
groovy.lang.MissingPropertyException: No such property: BRANCH for class: groovy.lang.Binding

# Possible Implementation
Not obligatory, but suggest an idea for implementing addition or change

**Comment by cdelmonte-zg** [comment]
going to be released.
