### ISSUE TITLE
repo:push to feature branch do not trigger builds

### ISSUE THREAD

**Issue by arohithr8** [jenkinsci/bitbucket-push-and-pull-request-plugin#54]
* Plugin Version: 2.0.0
* Jenkins Version: 2.176.1
* Jenkins Job Type: Pipeline
* Triggered via: Bitbucket Cloud

# Expected Behavior
When a BitBucket webhook for repo:push is configured and sent to Jenkins/plugin a build is triggered for specific branch (master, feature)

# Actual Behavior
No build is triggered for branches other than the master branch.

# Possible Solution
find a way to trigger branches with all names

# Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug
1. setup BitBucket webhook for repo:push events
1. setup jenkins scm for repo and branch 'master, feature/*'
1.etup build trigger for plugin "Push" allowed branches 'master, feature/*'
1. Make pushes to feature branch which should trigger build for feature branch

# Context
Changes in feature branch are not noticed until a PR is created and jenkins build is triggered by PR.

## Bitbucket payload
Only if relevant, will be helpful for reproducing the issue

## Jenkins Job configuration
![image](https://user-images.githubusercontent.com/46582843/62711750-33c5bd80-b9bf-11e9-8906-0eed548f1199.png)

source checkout in jenkins job:
git branch: '**', credentialsId: 'bitbucket_cred', url: 'https://bitbucket.org/reponame'

## Jenkins logs

INFO Following allowed branches patterns are set: feature/*, feature/testfeature1, 
INFO The branchName in action is: feature/testfeature1
INFO Matching branch: feature/testfeature1 with branchSpec pattern: feature/*
INFO Should schedule job : true and (polling result has changes **false** or is pull request false)

**Comment by AdallomRoy** [comment]
Happens to me as well, this is a bug that was introduced in one of the latest versions - started happening after updated plugin version.

**Comment by arohithr8** [comment]
Yes, giving exact branch works, but I need it to be workinf for multiple short lived feature branches.

**Comment by cdelmonte-zg** [comment]
Hi @AdallomRoy 

did you take a look to this test class: io.jenkins.plugins.bitbucketpushandpullrequest.filter.repository.BitBucketPPRRepositoryPushActionFilterTest

you can find there some use cases... Maybe does it help?

**Comment by arohithr8** [comment]
#39
