### ISSUE TITLE
Filter branches for the trigger - Pull Request events

### ISSUE THREAD

**Issue by jchristheodore** [jenkinsci/bitbucket-push-and-pull-request-plugin#61]
# Feature Request
Plugin Version: 2.2.0

<img width="928" alt="Screen Shot 2019-10-17 at 10 28 49 pm" src="https://user-images.githubusercontent.com/20987935/67005114-91982380-f12d-11e9-8051-8234b06b340a.png">

# Expected Behaviour
This plugin should trigger the build only for the specific branch for which the pull request has been created / updated / approved / merged.

# Actual Behaviour
When a pull request is created / updated / approved / merged it ends up triggering build for all the branches.

**Comment by mixMugz** [comment]
Same problem here. Have 3 main branches release/dev/test. All PR in dev automaticaly triggered other branches to build.
