### ISSUE TITLE
bitbucketRepositoryPushAction missing signature

### ISSUE THREAD

**Issue by ScOut3R** [jenkinsci/bitbucket-push-and-pull-request-plugin#65]
# Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There is no existing issue regarding the same topic

* Plugin Version: 2.2.0
* Jenkins Version: 2.190.2
* Jenkins Job Type: Freestyle
* Triggered via: Bitbucket Cloud

# Expected Behavior
Job DSL parsed successfully.

# Actual Behavior
Job DSL parsing complains that
```
No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.bitbucketRepositoryPushAction() is applicable for argument types: (java.lang.Boolean, java.lang.String)
```

# Possible Solution
Downgrading to 2.0.0 resolves the issue.

# Steps to Reproduce
Job DSL configuration
``` 
triggers {
    bitbucketRepositoryPushAction(false, 'staging')
}
```

# Context
Using the Job DSL plugin to manage the Jenkins job configuration.

**Comment by rhotau** [comment]
Hi @ScOut3R,

Does plug-in 2.2.0 work when you do the following in your job-dsl config instead?
```
triggers {
  bitbucketTriggers {
    repositoryPushAction(false, 'staging')
  }
}
```

**Comment by ScOut3R** [comment]
Hi @rhotau ,

thank you for your response. I've updated the plugin to version 2.2.0 and the configuration as you suggested and now experiencing the following error:
```
ERROR: (fetch_scheduled_tasks.groovy, line 11) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.repositoryPushAction() is applicable for argument types: (java.lang.Boolean, java.lang.String) values: [false, staging]
```

**Comment by rhotau** [comment]
Hi @ScOut3R,

Apologies, I noticed that in fact a third parameter was added to the function signature (extra `triggerAlsoIfNothingChanged` parameter as second boolean argument). If I finally narrowed it down, the following should work (I'd be tempted to say that it should be set to false):
```
triggers {
  bitbucketTriggers {
    repositoryPushAction(false, false, 'staging')
  }
}
```

**Comment by ScOut3R** [comment]
Thank you @rhotau , this worked for me. It's all sorted now. I appreciate your help!
