### ISSUE TITLE
Trigger Configurations always change

### ISSUE THREAD

**Issue by erginipekci7** [jenkinsci/bitbucket-push-and-pull-request-plugin#67]
* Plugin Version: 2.2.0
* Jenkins Version: 2.196
* Jenkins Job Type: Pipeline
* Triggered via: Bitbucket Cloud

I configured to Build with BitBucket Push and Pull Request Plugin Trigger for Created an Update. When I look later,there was only created option. I should add update or created options. Maybe it doesn't save correctly.

The trigger must be stable, it shouldn't change random. Are there any way to trigger this job? Bitbucket hook doesn't work. (for example this plugin for example environment variable doesn't work)

**Comment by macghriogair** [comment]
Hey @erginipekci7 , 
we appreciate your feedback!
is this still an issue for you with the latest release?
And if so, could you please provide steps how to reproduce this?
Thanks!

**Comment by cdelmonte-zg** [comment]
Closing. You can reopen it if it is still relevant for you.
