### ISSUE TITLE
Jobs are not triggered on push event

### ISSUE THREAD

**Issue by RonaHirsch** [jenkinsci/bitbucket-push-and-pull-request-plugin#68]
Plugin Version: 2.0.0
Jenkins Version: 2.150.3
Jenkins Job Type: Pipeline
Triggered via: Bitbucket Cloud

# Expected Behavior
Job should be triggered on push event.

# Actual Behavior
Job is not triggered on Jenkins. 
However, the webhook is executed. I get a 200 http response and "ok" in the response body.

# Context
The plugin is not working. Though the webhook is triggered and seems ok, Jenkins jobs are not running.

**Comment by cdelmonte-zg** [comment]
May you provide more details after upgrading to the latest release (2.2.0)?

**Comment by ofirshtrull** [comment]
Hi @cdelmonte-zg ,
I work with @RonaHirsch  our version is 2.2.0 and we still experience this problem

**Comment by macghriogair** [comment]
Closing this issue, kindly re-open if this is still relevant.
