### ISSUE TITLE
BITBUCKET_PAYLOD

### ISSUE THREAD

**Issue by mkryva** [jenkinsci/bitbucket-push-and-pull-request-plugin#7]
```BITBUCKET_PAYLOAD=io.jenkins.plugins.bitbucketpushandpullrequest.model.BitBucketPPRNewPayload@1a554b37```

Currently BITBUCKET_PAYLOAD stored java object reference in envrionment. 
I think It would be string.

**Comment by cdelmonte-zg** [comment]
Hi @ mkryva  Which infos do you need to retrieve from the payload?

**Comment by mkryva** [comment]
Author of PR for example and hash of source commit. It would be better to get source payload from bitbucket

**Comment by cdelmonte-zg** [comment]
@ mkryva please, install the bitbucket-push-and-pull-request version 1.4.1
Now the BITBUCKET_PAYLOAD injection should work
