### ISSUE TITLE
http://jenkins_IP_or_host:8080/job/Job_Name/BitBucketPollLog/ is not available

### ISSUE THREAD

**Issue by oviupstack** [jenkinsci/bitbucket-push-and-pull-request-plugin#71]
# Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There is no existing issue regarding the same topic

* Plugin Version: 2.2.1
* Jenkins Version: 2.190.3
* Jenkins Job Type: Freestyle
* Triggered via: Bitbucket Cloud

# Expected Behavior
When I visit http://jenkins_IP_or_host:8080/job/Job_Name/BitBucketPollLog/ is should load the log of requests coming from bitbucket

# Actual Behavior
visiting the link results in a jenkins generic 404 error

**Comment by cdelmonte-zg** [comment]
Thanks, fixed. It will be added in the next release.
