### ISSUE TITLE
Build option is not showing anything on Jenkins ver. 2.190.3

### ISSUE THREAD

**Issue by nishu876mishra** [jenkinsci/bitbucket-push-and-pull-request-plugin#80]
Whenever I am trying to trigger build now for my project its giving blank screen as :

Stage View
No data available. This Pipeline has not yet run.

- I am not able to figure out why its giving this error.

**Comment by cdelmonte-zg** [comment]
Did you solve this issue?

**Comment by amine95bz** [comment]
i have the same issue.

**Comment by zhuanjiaozm** [comment]
i have the same issue.

**Comment by yise123** [comment]
i have the same issue..what shall I do?

**Comment by lofung** [comment]
same

**Comment by melakusisay** [comment]
I have the same issue is there anyway to reput the pipeline on the stage?
