### ISSUE TITLE
Doesn't work branch filter for Cloud BitBucket pull requests

### ISSUE THREAD

**Issue by Pleshchuk** [jenkinsci/bitbucket-push-and-pull-request-plugin#86]
I have installed Jenkins version 2.204.1 and bitbucket push and pull request plugin version 2.2.1
When I create a Jenkins job or pipeline the filter for PR's is not working.
I have tried Jenkins versions 2.204.1 and the older one 2.150.1 and received the same issue for both.
![image](https://user-images.githubusercontent.com/20129287/74148633-961da600-4c0e-11ea-90ea-e4c94fccd1ea.png)
![image](https://user-images.githubusercontent.com/20129287/74148651-a03fa480-4c0e-11ea-952e-26a36abebcb0.png)
![image](https://user-images.githubusercontent.com/20129287/74148691-b51c3800-4c0e-11ea-9d02-d4717696b6f2.png)

**Comment by cdelmonte-zg** [comment]
Hi @Pleshchuk , please install the plugin version 2.3.0. to enable this feature, thanks.
