### ISSUE TITLE
No job is triggered after recieving hook from Bitbucket on newest Jenkins 2.224

### ISSUE THREAD

**Issue by brx19** [jenkinsci/bitbucket-push-and-pull-request-plugin#96]
After updating Jenkins to 2.224 Bitbucket hook that is successful no longer triggers the jobs. Here is the partial log:
![obraz](https://user-images.githubusercontent.com/23616759/76441321-820cc600-63bf-11ea-87d0-cdd07d0a4a0e.png)

After that all jobs are listed, but none is triggered.
Here is what I have in the job (it has been recreated from scratch):
![obraz](https://user-images.githubusercontent.com/23616759/76441492-cc8e4280-63bf-11ea-92c0-3a9f86fef217.png)

Bitbucket side:
![obraz](https://user-images.githubusercontent.com/23616759/76441723-2abb2580-63c0-11ea-8e4b-5b6939db083c.png)

It was working fine before the update. Plugin is in 2.3.0 version.

**Comment by cdelmonte-zg** [comment]
Hi @brx19 I tried it and all is still working... want you try with the last release 2.3.1.? Maybe something changed...
Let me know

**Comment by zyhagit** [comment]
> Hi @brx19 I tried it and all is still working... want you try with the last release 2.3.1.? Maybe something changed...
> Let me know

Hi @cdelmonte-zg , I met the hook not work issue too.
 I am using Bitbucket Server 7.0.1 + Jenkins 2.219 + plugin 2.3.1
And I am investigating the cause of the problem, maybe I am using a wrong configuration. Could you please provide a workable Jenkins and Plugin version?
Thanks!

**Comment by cdelmonte-zg** [comment]
@heathergithub Thank you for reporting the issue. What do you mean with "workable jenkins and Plugin version? If I understand it in the right way:
plugin version ist the last one: 2.3.1 
Jenkins version, which we are actually using to test is the 2.225.
BitBucket Server is still the version 6.10. We are going to upgrade to 7.1.0

**Comment by heathergithub** [comment]
> 
> 
> @heathergithub Thank you for reporting the issue. What do you mean with "workable jenkins and Plugin version? If I understand it in the right way:
> plugin version ist the last one: 2.3.1
> Jenkins version, which we are actually using to test is the 2.225.
> BitBucket Server is still the version 6.10. We are going to upgrade to 7.1.0

Thanks @cdelmonte-zg , that's the information I need.

**Comment by brx19** [comment]
Because of this issue I have switched to addon installed directly on BitBucket server, and it works perfeclty even with new versions of Jenkins.

**Comment by cdelmonte-zg** [comment]
@heathergithub you are welcome :)

@brx19 which plugin you are referring to?

**Comment by cdelmonte-zg** [comment]
@heathergithub a new version is out 2.3.2 with tested support for bitbucket 7
