### ISSUE TITLE
New "Source branch updated" PR Webhook/Event supported in BBS 7.0

### ISSUE THREAD

**Issue by timblaktu** [jenkinsci/bitbucket-push-and-pull-request-plugin#97]
Any plans to support this new webhook/event which will enable a clean separation between "anything changed in the PR (including comments) vs "a commit has been made to the source branch"?

I assume your pullRequestServerUpdatedAction operates on the latter, and is "noisy" in the sense that it will trigger even when comments change.

Details on new webhook here:
https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html

**Comment by cdelmonte-zg** [comment]
Hi @timblaktu ,

thank you for the hint!
We'll implement in the release 2.3.2
