### ISSUE TITLE
Webhook does not trigger build on pull request creation

### ISSUE THREAD

**Issue by jmmen1** [jenkinsci/bitbucket-push-and-pull-request-plugin#98]
I'm trying to configure a webhook in BitBucket Server to trigger a build in Jenkins when a pull request is created.

I followed the instructions at this link to setup the webhook: https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html

But the instructions do not provide details as to what URL on the Jenkins side should be triggered. I configured the webhook to use the polling URL as mentioned in the build job REST API.

When I test the webhook connection, it is successful, but in Jenkins, the build is not started. The BitBucket Push and Pull Request Hook Log says:

> Polling has not run yet.

Is this an issue with how I configured the webhook? If so, can you provide any help in configuring the BitBucket side for this to work?

This is the webhook configuration in Bitbucket:
<img width="1311" alt="bitbucket_config" src="https://user-images.githubusercontent.com/12653977/77005231-7294fc00-692e-11ea-91c0-d4116997f69d.png">

This is the trigger configuration in Jenkins:
<img width="1212" alt="jenkins_config" src="https://user-images.githubusercontent.com/12653977/77005253-7de82780-692e-11ea-92a3-d062eadf0a8b.png">

This project is not configured using Pipelines. Instead it's a Freestyle project. 

Thanks!

**Comment by cdelmonte-zg** [comment]
Hi @jmmen1 
the webhook configuration in BB is JENKINS_URL + "/bitbucket-hook/"

**Comment by jmmen1** [comment]
Thanks for the response. I was able to get it working.

The README is a little misleading. I'm running Bitbucket Server, but the README only mentions appending "/bitbucket-hook/" to the Jenkins URL if you are using Bitbucket Cloud.

**Comment by cdelmonte-zg** [comment]
Hi @jmmen1, thank you for the feedback. We'll fix the README with the next release.
